-- SOZU Legal Flow — esquema base para el Pipeline de Contratos
--
-- Conecta las etapas 2..6 del "Panel de Operaciones" de SOZU Legal Flow a
-- datos reales. La etapa 1 ("Solicitud recibida") sigue derivándose de
-- cuentas_cobranza + propiedades.id_estatus_disponibilidad = 4 (Apartado);
-- no existe row aquí hasta que el operador da "Revisar →".
--
-- Relación: una cuenta puede tener varios expedientes (contrato original,
-- modificatorios, prórrogas, terminación) ⇒ legal_flow_expedientes es 1:N
-- contra cuentas_cobranza.
--
-- Ref spec: Ejecuciones/ejecutar.md (Ramón, 2026-05-30).
-- Notas de diseño:
--   * cuentas_cobranza.id es bigint en el baseline ⇒ la FK usa bigint
--     (el .md decía integer — corregido para evitar mismatch de tipos).
--   * Todos los valores de datos van en español ("Primera mayúscula con
--     espacios"). Los códigos enum del frontend (src/types/legal-flow.ts:
--     CaseStatus, RequestType, Priority) deben actualizarse para coincidir.
--   * Las 3 tablas llevan campos de control (activo, fecha_creacion,
--     fecha_actualizacion). fecha_actualizacion se refresca en cada UPDATE
--     vía trigger genérico.

-- 0) Función genérica: refresca fecha_actualizacion en cada UPDATE.

CREATE OR REPLACE FUNCTION public.legal_flow_actualizar_fecha_modificacion()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.fecha_actualizacion := now();
  RETURN NEW;
END;
$$;


-- 1) Catálogo de etapas. El codigo (PK) es el valor en español que también
--    usa el frontend como enum CaseStatus. Mantener sincronizado.

CREATE TABLE IF NOT EXISTS public.legal_flow_etapas (
  codigo text PRIMARY KEY,
  nombre text NOT NULL,
  orden  smallint NOT NULL,
  es_terminal boolean NOT NULL DEFAULT false,
  activo boolean NOT NULL DEFAULT true,
  fecha_creacion timestamptz NOT NULL DEFAULT now(),
  fecha_actualizacion timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.legal_flow_etapas (codigo, nombre, orden, es_terminal) VALUES
  ('Solicitud recibida',   'Solicitud recibida',   1, false),
  ('Información faltante',  'Información faltante',  2, false),
  ('En revisión legal',    'En revisión legal',     3, false),
  ('Aprobado',             'Aprobado',              4, false),
  ('Firma cliente',        'Firma cliente',         5, false),
  ('Firma titular',        'Firma titular',         6, false),
  ('En firma',             'En firma',              7, false),
  ('Parcialmente firmado', 'Parcialmente firmado',  8, false),
  ('Firmado',              'Firmado',               9, true),
  ('Rechazado',            'Rechazado',            90, true),
  ('Cancelado',            'Cancelado',            91, true),
  ('Archivado',            'Archivado',            92, true)
ON CONFLICT (codigo) DO NOTHING;

DROP TRIGGER IF EXISTS legal_flow_etapas_set_fecha_actualizacion ON public.legal_flow_etapas;
CREATE TRIGGER legal_flow_etapas_set_fecha_actualizacion
  BEFORE UPDATE ON public.legal_flow_etapas
  FOR EACH ROW EXECUTE FUNCTION public.legal_flow_actualizar_fecha_modificacion();


-- 2) Expedientes legales — header de cada caso.

CREATE TABLE IF NOT EXISTS public.legal_flow_expedientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_cuenta_cobranza BIGINT NOT NULL REFERENCES public.cuentas_cobranza(id),
  -- Tipo de solicitud (match con frontend RequestType en legal-flow.ts):
  -- Nuevo contrato | Nuevo convenio | Modificatorio | Renovación | Terminación | Validación externa
  tipo_solicitud text NOT NULL DEFAULT 'Nuevo contrato',
  etapa text NOT NULL DEFAULT 'En revisión legal'
    REFERENCES public.legal_flow_etapas(codigo),
  prioridad text NOT NULL DEFAULT 'Medio' CHECK (prioridad IN ('Alto','Medio','Bajo')),
  titulo text,
  descripcion text,
  -- Asignación + autoría: guardamos email para evitar acoplamiento fuerte
  -- contra usuarios; si se quiere FK estricta cambiar a
  -- id_usuario_asignado INTEGER REFERENCES usuarios(id).
  email_asignado text,
  email_solicitante text NOT NULL,
  -- Template usado (opcional, FK suave a tabla de templates si se crea luego).
  id_template integer,
  -- Fechas del proceso
  fecha_limite timestamptz,
  fecha_aprobacion timestamptz,
  fecha_envio_firma timestamptz,
  fecha_firmado timestamptz,
  notas_rechazo text,
  -- Campos de control
  activo boolean NOT NULL DEFAULT true,
  fecha_creacion timestamptz NOT NULL DEFAULT now(),
  fecha_actualizacion timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS legal_flow_expedientes_cuenta_idx
  ON public.legal_flow_expedientes (id_cuenta_cobranza);
CREATE INDEX IF NOT EXISTS legal_flow_expedientes_etapa_idx
  ON public.legal_flow_expedientes (etapa) WHERE activo;
CREATE INDEX IF NOT EXISTS legal_flow_expedientes_asignado_idx
  ON public.legal_flow_expedientes (email_asignado) WHERE activo;


-- 3) Histórico de transiciones — audit log.

CREATE TABLE IF NOT EXISTS public.legal_flow_historico (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_expediente bigint NOT NULL REFERENCES public.legal_flow_expedientes(id) ON DELETE CASCADE,
  etapa_anterior text REFERENCES public.legal_flow_etapas(codigo),
  etapa_nueva text NOT NULL REFERENCES public.legal_flow_etapas(codigo),
  fecha timestamptz NOT NULL DEFAULT now(),
  email_usuario text NOT NULL,
  notas text,
  -- Campos de control
  activo boolean NOT NULL DEFAULT true,
  fecha_creacion timestamptz NOT NULL DEFAULT now(),
  fecha_actualizacion timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS legal_flow_historico_expediente_idx
  ON public.legal_flow_historico (id_expediente, fecha DESC);

DROP TRIGGER IF EXISTS legal_flow_historico_set_fecha_actualizacion ON public.legal_flow_historico;
CREATE TRIGGER legal_flow_historico_set_fecha_actualizacion
  BEFORE UPDATE ON public.legal_flow_historico
  FOR EACH ROW EXECUTE FUNCTION public.legal_flow_actualizar_fecha_modificacion();


-- 4) Trigger de bitácora: cada INSERT o cambio de `etapa` en un expediente
--    registra una fila en el histórico.

CREATE OR REPLACE FUNCTION public.legal_flow_registrar_cambio_etapa()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO public.legal_flow_historico (
      id_expediente, etapa_anterior, etapa_nueva, email_usuario
    ) VALUES (
      NEW.id, NULL, NEW.etapa, COALESCE(NEW.email_asignado, NEW.email_solicitante)
    );
    RETURN NEW;
  ELSIF OLD.etapa IS DISTINCT FROM NEW.etapa THEN
    INSERT INTO public.legal_flow_historico (
      id_expediente, etapa_anterior, etapa_nueva, email_usuario
    ) VALUES (
      NEW.id, OLD.etapa, NEW.etapa, COALESCE(NEW.email_asignado, NEW.email_solicitante)
    );
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS legal_flow_expedientes_etapa_change ON public.legal_flow_expedientes;
CREATE TRIGGER legal_flow_expedientes_etapa_change
  AFTER INSERT OR UPDATE OF etapa ON public.legal_flow_expedientes
  FOR EACH ROW EXECUTE FUNCTION public.legal_flow_registrar_cambio_etapa();

-- Refresca fecha_actualizacion en cualquier UPDATE del expediente.
DROP TRIGGER IF EXISTS legal_flow_expedientes_set_fecha_actualizacion ON public.legal_flow_expedientes;
CREATE TRIGGER legal_flow_expedientes_set_fecha_actualizacion
  BEFORE UPDATE ON public.legal_flow_expedientes
  FOR EACH ROW EXECUTE FUNCTION public.legal_flow_actualizar_fecha_modificacion();
