-- Tablas de actividad del CRM: notas y tareas por contacto.
-- Un "contacto" del CRM = una fila de `entidades_relacionadas` (prospecto tipo 7 /
-- comprador tipo 2). Estas tablas cuelgan de `id_entidad_relacionada`.

-- ─── crm_notas ────────────────────────────────────────────────────────────────
CREATE TABLE public.crm_notas (
    id                      INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_entidad_relacionada  BIGINT       NOT NULL
        REFERENCES public.entidades_relacionadas(id) ON DELETE CASCADE,
    id_usuario              UUID,        -- auth_user_id del autor
    contenido               TEXT         NOT NULL,   -- HTML de la nota
    fecha_actividad         DATE,        -- fecha que marca el usuario (opcional)
    activo                  BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion          TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_crm_notas_er ON public.crm_notas (id_entidad_relacionada);

-- ─── crm_tareas ───────────────────────────────────────────────────────────────
CREATE TABLE public.crm_tareas (
    id                      INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_entidad_relacionada  BIGINT       NOT NULL
        REFERENCES public.entidades_relacionadas(id) ON DELETE CASCADE,
    id_usuario_asignado     UUID,        -- auth_user_id del asesor
    titulo                  TEXT         NOT NULL,
    tipo                    TEXT         NOT NULL DEFAULT 'seguimiento', -- seguimiento, llamada, email, whatsapp, visita
    prioridad               TEXT         NOT NULL DEFAULT 'normal',      -- baja, normal, alta, urgente
    estatus                 TEXT         NOT NULL DEFAULT 'pendiente',   -- pendiente, en_progreso, completada, cancelada
    fecha_vencimiento       DATE,
    activo                  BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    fecha_actualizacion     TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_crm_tareas_er ON public.crm_tareas (id_entidad_relacionada);
CREATE INDEX idx_crm_tareas_asignado ON public.crm_tareas (id_usuario_asignado);

-- Trigger fecha_actualizacion automática para crm_tareas
CREATE OR REPLACE FUNCTION public.set_crm_tareas_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.fecha_actualizacion = NOW();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_crm_tareas_updated_at
BEFORE UPDATE ON public.crm_tareas
FOR EACH ROW EXECUTE FUNCTION public.set_crm_tareas_updated_at();

-- ─── Row Level Security ───────────────────────────────────────────────────────
-- Actividad interna del equipo de ventas: lectura/escritura para autenticados,
-- borrado solo admin.
ALTER TABLE public.crm_notas  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crm_tareas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "crm_notas_select" ON public.crm_notas
    FOR SELECT TO authenticated USING (true);
CREATE POLICY "crm_notas_insert" ON public.crm_notas
    FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "crm_notas_update" ON public.crm_notas
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "crm_notas_delete" ON public.crm_notas
    FOR DELETE TO authenticated USING (is_admin_user());

CREATE POLICY "crm_tareas_select" ON public.crm_tareas
    FOR SELECT TO authenticated USING (true);
CREATE POLICY "crm_tareas_insert" ON public.crm_tareas
    FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "crm_tareas_update" ON public.crm_tareas
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "crm_tareas_delete" ON public.crm_tareas
    FOR DELETE TO authenticated USING (is_admin_user());
