-- Portal Embajadores Fase 1: tipos de documento del embajador
-- Fecha: 2026-06-01
--
-- Los documentos del embajador (convenio, identificación, datos bancarios) se migran del
-- jsonb embajadores_config.documentos_pago a la tabla documentos. Se requieren estos tipos.
-- "Constancia de situación fiscal" ya existe (id 6) y se reutiliza.
--
-- tipos_documento.id es GENERATED BY DEFAULT AS IDENTITY -> se omite el id (lo asigna la
-- secuencia). id_categoria_documento = 4 (categoría de documentos de persona, igual que la
-- constancia fiscal). asignado_a='per', padre='a' (aplica a personas físicas y morales).
-- Inserts idempotentes vía WHERE NOT EXISTS.

INSERT INTO public.tipos_documento (nombre, id_categoria_documento, asignado_a, padre, activo)
SELECT v.nombre, 4, 'per', 'a', true
FROM (VALUES
  ('Convenio de Embajador firmado'),
  ('Identificación oficial'),
  ('Datos bancarios')
) AS v(nombre)
WHERE NOT EXISTS (
  SELECT 1 FROM public.tipos_documento t WHERE t.nombre = v.nombre
);
