-- Homologación CRM ↔ Portal Agente — 07: alta con dueño automático y reasignación de leads
-- Fecha: 2026-08-07
-- REQUIERE: el 04 (helpers fn_auth_user_de_persona / fn_persona_de_auth_user y los triggers
--           de sincronía de dueño). El resto de la carpeta no es obligatorio para éste.
--
-- Cierra dos huecos operativos:
--   1. Todo prospecto nace con dueño, entre por donde entre (Portal Agente, CRM, carga
--      masiva, webhook de Meta). Por defecto el dueño es quien lo crea.
--   2. Un lead se puede transferir: quien lo transfiere lo pierde, y queda registro de quién
--      movió qué, a quién y cuándo. La bitácora no se borra: sustenta disputas de comisión.
--
-- ─── Verificado read-only contra prod (tzmhgfjmddkfyffkkmto, 2026-08-07) ──────
--   * `crm_current_user_is_agente_externo()` existe: el `origen = 'agente_externo'` no es
--     decorativo, es lo que hace que el rol 40 vea en el CRM los leads que él mismo dio de
--     alta (filtro server-side de `get_crm_contactos_agrupados`, migración 20260805030000).
--   * Roles tal cual los describe el documento: 1 Super Administrador · 3 Agente Inmobiliario
--     (335 usuarios activos) · 4 Inmobiliaria (832) · 9 Agente Interno (2) · 31 Supervisor
--     agentes externos (1) · 40 Agente Externo (1). Confirmado que el 3 NO es «Agente
--     Interno»: manda la base, no el CLAUDE.md.
--   * `puede_impersonar` es true en los roles 1, 2 y 31 — o sea que `current_puede_impersonar()`
--     abarca más que `is_admin_user()` (roles 1 y 2), incluido el supervisor de externos.
--   * `crm_leads_reasignaciones` no existe todavía.
--   * `entidades_relacionadas.id` es bigint (máximo actual 6,798).
--
-- ─── Cinco correcciones respecto al documento ────────────────────────────────
-- 1. CADA REASIGNACIÓN DEJABA DOS RENGLONES. `reasignar_lead` escribe la bitácora, y acto
--    seguido el trigger del 04 propaga el dueño a `entidades_relacionadas`, lo que dispara
--    `trg_crm_auditar_cambio_dueno` y escribe un SEGUNDO renglón del mismo evento. Una
--    bitácora que duplica sirve de poco en una disputa. Se resuelve con una bandera de
--    transacción (`crm.reasignacion`) que la RPC levanta y el trigger respeta.
-- 2. TIPOS bigint. La tabla declaraba `id_entidad_relacionada integer` con FK a una columna
--    bigint, y la RPC recibía integer. Alineado a bigint en los dos lados.
-- 3. SE IMPORTAN LOS 12 CONFLICTOS DEL 04. Como el 04 corre antes y la bitácora todavía no
--    existía, ahí los respaldos quedaron en `_bak_conflicto_dueno_lead_20260807`. Este archivo
--    los sube a la bitácora definitiva, así que el historial queda completo desde el día uno.
-- 4. LA REASIGNACIÓN AHORA SÍ MUEVE LOS NEGOCIOS. `crm_negocios.id_usuario_propietario` lo
--    llena el 05 con el creador de la oferta y nadie lo actualizaba: tras un traspaso, el
--    tablero «Negocios» seguía mostrándoselos al agente anterior (por eso el 06 tuvo que
--    aceptar los dos dueños). Se agrega el trigger que lo propaga, y la columna deja de mentir.
-- 5. CÓDIGO MUERTO FUERA. El trigger de auditoría hacía `coalesce(fn_auth_user_de_persona(...),
--    '000...0')` bajo un WHERE que exige justamente que eso no sea NULL: el coalesce nunca
--    podía dispararse.
--
-- Orden de preferencia del dueño en el alta: (1) `auth.uid()` de quien inserta; (2) sin sesión
-- —service_role: webhooks, cargas—, el usuario de `id_persona_duena_lead` si viene informado;
-- (3) si no hay ninguno, queda sin dueño y se reparte a mano. No se inventa propietario.
--
-- Nota de convivencia con el 04: en un alta que traiga `id_persona_duena_lead`, primero corre
-- `trg_crm_lead_autoasignar` (dueño = quien inserta) y después `trg_crm_sync_dueno_desde_er`
-- (dueño = el agente indicado), que gana. Es lo correcto: lo explícito pisa a lo implícito.
--
-- Idempotente: CREATE TABLE/INDEX IF NOT EXISTS, CREATE OR REPLACE, DROP TRIGGER IF EXISTS.
-- Sin BEGIN/COMMIT (el CI envuelve cada migración en transacción).

-- ─────────────────────────────────────────────────────────────────────
-- 1. Bitácora de reasignaciones
-- ─────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.crm_leads_reasignaciones (
  id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_entidad_relacionada bigint NOT NULL REFERENCES public.entidades_relacionadas(id),
  de_propietario         uuid,
  a_propietario          uuid NOT NULL,
  id_usuario_ejecuta     uuid,
  motivo                 text,
  fecha_creacion         timestamp without time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS crm_leads_reasig_er_idx
  ON public.crm_leads_reasignaciones (id_entidad_relacionada, fecha_creacion DESC);

COMMENT ON TABLE public.crm_leads_reasignaciones IS
  'Bitácora de transferencias de lead entre agentes. No se borra: sustenta disputas de comisión.';

-- `anon` conserva `arwdDxtm` sobre las tablas del CRM: la migración 20260806100000 solo cubrió
-- 4 tablas de su fase 0 y dejó fuera a `crm_leads_atribucion` y compañía. Una tabla nueva
-- hereda esos privilegios por default, así que se revocan aquí explícitamente.
REVOKE ALL ON public.crm_leads_reasignaciones FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON public.crm_leads_reasignaciones FROM authenticated;
GRANT SELECT ON public.crm_leads_reasignaciones TO authenticated;

ALTER TABLE public.crm_leads_reasignaciones ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS crm_leads_reasig_lectura ON public.crm_leads_reasignaciones;
CREATE POLICY crm_leads_reasig_lectura ON public.crm_leads_reasignaciones
  FOR SELECT TO authenticated
  USING (
    de_propietario = auth.uid()
    OR a_propietario = auth.uid()
    OR public.current_puede_impersonar()
  );
-- Sin policy de INSERT/UPDATE/DELETE: solo escribe la RPC (SECURITY DEFINER).

-- ─────────────────────────────────────────────────────────────────────
-- 2. Importar los conflictos que el 04 dejó respaldados (corrección 3)
-- ─────────────────────────────────────────────────────────────────────
DO $$
DECLARE v_n int := 0;
BEGIN
  IF to_regclass('public._bak_conflicto_dueno_lead_20260807') IS NULL THEN RETURN; END IF;

  INSERT INTO public.crm_leads_reasignaciones
    (id_entidad_relacionada, de_propietario, a_propietario, id_usuario_ejecuta, motivo, fecha_creacion)
  SELECT b.id_entidad_relacionada, b.auth_portal, b.auth_crm, NULL,
         'conflicto_homologacion: gana el propietario del CRM (migración 20260807040000)',
         b.fecha
  FROM public._bak_conflicto_dueno_lead_20260807 b
  WHERE b.auth_crm IS NOT NULL
    AND NOT EXISTS (
      SELECT 1 FROM public.crm_leads_reasignaciones r
      WHERE r.id_entidad_relacionada = b.id_entidad_relacionada
        AND r.motivo LIKE 'conflicto_homologacion%');
  GET DIAGNOSTICS v_n = ROW_COUNT;

  IF v_n > 0 THEN
    RAISE NOTICE 'Conflictos de dueño importados a la bitácora: %', v_n;
  END IF;
END $$;

-- ─────────────────────────────────────────────────────────────────────
-- 3. Alta: todo lead nace con dueño
-- ─────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.fn_crm_lead_autoasignar()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_auth   uuid;
  v_origen text;
BEGIN
  IF NEW.id_tipo_entidad <> 7 OR NOT NEW.activo THEN
    RETURN NEW;
  END IF;

  v_auth := auth.uid();
  IF v_auth IS NULL THEN
    v_auth   := public.fn_auth_user_de_persona(NEW.id_persona_duena_lead);
    v_origen := 'sistema';
  ELSIF public.crm_current_user_is_agente_externo() THEN
    -- CRÍTICO: el RPC get_crm_contactos_agrupados restringe al rol «Agente Externo» a ver SOLO
    -- los leads con origen='agente_externo' (migración 20260805030000). Con otro origen, el
    -- externo dejaría de ver en el CRM los prospectos que él mismo acaba de dar de alta.
    v_origen := 'agente_externo';
  ELSE
    v_origen := 'portal_agente';
  END IF;

  IF v_auth IS NULL THEN
    RETURN NEW;                         -- sin dueño: se reparte en CRM > Asignación
  END IF;

  -- No escribe estado: `estatus_lead` es NOT NULL DEFAULT 'nuevo' y el trigger del CRM
  -- deriva `id_estatus_lead` en el mismo INSERT.
  INSERT INTO public.crm_leads_atribucion (id_entidad_relacionada, id_propietario, origen, activo)
  VALUES (NEW.id, v_auth, v_origen, true)
  ON CONFLICT (id_entidad_relacionada) DO UPDATE
    SET id_propietario = EXCLUDED.id_propietario
    WHERE public.crm_leads_atribucion.id_propietario IS NULL;   -- nunca pisa un dueño ya puesto

  RETURN NEW;

EXCEPTION WHEN OTHERS THEN
  RAISE WARNING 'fn_crm_lead_autoasignar (er=%): %', NEW.id, SQLERRM;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_crm_lead_autoasignar ON public.entidades_relacionadas;
CREATE TRIGGER trg_crm_lead_autoasignar
AFTER INSERT ON public.entidades_relacionadas
FOR EACH ROW EXECUTE FUNCTION public.fn_crm_lead_autoasignar();

-- ─────────────────────────────────────────────────────────────────────
-- 4. Auditar TODO cambio de dueño, venga por donde venga
--    `NewOfferDialog.tsx` y `NewProductOfferDialog.tsx` reescriben id_persona_duena_lead al
--    creador de la oferta: generar una oferta le quita el lead a quien lo tenía, sin registro.
--    Este trigger no lo impide —es decisión de negocio, ver el pendiente al final— pero lo
--    deja asentado.
--    La bandera `crm.reasignacion` evita el renglón duplicado cuando el cambio viene de
--    reasignar_lead() (corrección 1).
-- ─────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.fn_crm_auditar_cambio_dueno()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_auth_nuevo uuid;
BEGIN
  IF NEW.id_tipo_entidad <> 7 THEN RETURN NEW; END IF;
  IF NEW.id_persona_duena_lead IS NOT DISTINCT FROM OLD.id_persona_duena_lead THEN
    RETURN NEW;
  END IF;

  -- El traspaso ya lo registró reasignar_lead(); esto es solo su propagación.
  IF coalesce(current_setting('crm.reasignacion', true), '') = '1' THEN
    RETURN NEW;
  END IF;

  v_auth_nuevo := public.fn_auth_user_de_persona(NEW.id_persona_duena_lead);
  IF v_auth_nuevo IS NULL THEN RETURN NEW; END IF;   -- sin destino mapeable no hay qué asentar

  INSERT INTO public.crm_leads_reasignaciones
    (id_entidad_relacionada, de_propietario, a_propietario, id_usuario_ejecuta, motivo)
  VALUES (NEW.id,
          public.fn_auth_user_de_persona(OLD.id_persona_duena_lead),
          v_auth_nuevo,
          auth.uid(),
          'cambio directo de id_persona_duena_lead');

  RETURN NEW;

EXCEPTION WHEN OTHERS THEN
  RAISE WARNING 'fn_crm_auditar_cambio_dueno (er=%): %', NEW.id, SQLERRM;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_crm_auditar_cambio_dueno ON public.entidades_relacionadas;
CREATE TRIGGER trg_crm_auditar_cambio_dueno
AFTER UPDATE OF id_persona_duena_lead ON public.entidades_relacionadas
FOR EACH ROW EXECUTE FUNCTION public.fn_crm_auditar_cambio_dueno();

-- ─────────────────────────────────────────────────────────────────────
-- 5. La reasignación arrastra los negocios de ese lead (corrección 4)
--    Sin esto, `crm_negocios.id_usuario_propietario` se queda con el creador de la oferta y el
--    tablero «Negocios» le sigue mostrando el negocio al agente anterior.
-- ─────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.fn_crm_sync_dueno_negocios()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NEW.id_propietario IS NULL THEN RETURN NEW; END IF;

  UPDATE public.crm_negocios
  SET id_usuario_propietario = NEW.id_propietario
  WHERE activo
    AND id_entidad_relacionada = NEW.id_entidad_relacionada
    AND id_usuario_propietario IS DISTINCT FROM NEW.id_propietario;

  RETURN NEW;

EXCEPTION WHEN OTHERS THEN
  RAISE WARNING 'fn_crm_sync_dueno_negocios (er=%): %', NEW.id_entidad_relacionada, SQLERRM;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_crm_sync_dueno_negocios ON public.crm_leads_atribucion;
CREATE TRIGGER trg_crm_sync_dueno_negocios
AFTER INSERT OR UPDATE OF id_propietario ON public.crm_leads_atribucion
FOR EACH ROW EXECUTE FUNCTION public.fn_crm_sync_dueno_negocios();

-- ─────────────────────────────────────────────────────────────────────
-- 6. Reasignar un lead (el dueño lo pierde, el destino lo gana)
-- ─────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.reasignar_lead(
  p_id_entidad_relacionada bigint,
  p_nuevo_propietario      uuid,
  p_motivo                 text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_auth     uuid    := auth.uid();
  v_actual   uuid;
  v_es_admin boolean := public.current_puede_impersonar();
BEGIN
  IF p_nuevo_propietario IS NULL THEN
    RAISE EXCEPTION 'Falta el agente destino' USING ERRCODE = '22023';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.usuarios u
    WHERE u.auth_user_id = p_nuevo_propietario AND u.activo
  ) THEN
    RAISE EXCEPTION 'El agente destino no existe o está dado de baja' USING ERRCODE = '22023';
  END IF;

  SELECT a.id_propietario INTO v_actual
  FROM public.crm_leads_atribucion a
  WHERE a.id_entidad_relacionada = p_id_entidad_relacionada AND a.activo;

  -- Puede reasignar el dueño actual o quien pueda impersonar. Un lead sin dueño lo toma
  -- cualquiera. Un agente NO puede arrebatarle un lead a otro.
  IF NOT v_es_admin AND v_actual IS NOT NULL AND v_actual IS DISTINCT FROM v_auth THEN
    RAISE EXCEPTION 'Este prospecto no te pertenece' USING ERRCODE = '42501';
  END IF;

  IF v_actual IS NOT DISTINCT FROM p_nuevo_propietario THEN
    RETURN;                              -- ya es de esa persona: no-op
  END IF;

  -- La bitácora la escribe esta función; el trigger de auditoría se hace a un lado mientras
  -- dura la transacción para no duplicar el evento (corrección 1).
  PERFORM set_config('crm.reasignacion', '1', true);

  INSERT INTO public.crm_leads_atribucion (id_entidad_relacionada, id_propietario, origen, activo)
  VALUES (p_id_entidad_relacionada, p_nuevo_propietario, 'reasignacion', true)
  ON CONFLICT (id_entidad_relacionada) DO UPDATE
    SET id_propietario = EXCLUDED.id_propietario;
  -- Los triggers del 04 propagan a entidades_relacionadas.id_persona_duena_lead y el de este
  -- archivo arrastra los negocios.

  INSERT INTO public.crm_leads_reasignaciones
    (id_entidad_relacionada, de_propietario, a_propietario, id_usuario_ejecuta, motivo)
  VALUES (p_id_entidad_relacionada, v_actual, p_nuevo_propietario, v_auth, nullif(trim(p_motivo), ''));

  PERFORM set_config('crm.reasignacion', '0', true);
END;
$$;

-- ─────────────────────────────────────────────────────────────────────
-- 7. Catálogo de destinos posibles
-- ─────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.get_agentes_asignables()
RETURNS TABLE (auth_user_id uuid, nombre text, email text, rol text)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT u.auth_user_id, u.nombre, u.email, r.nombre
  FROM public.usuarios u
  JOIN public.roles r ON r.id = u.rol_id
  WHERE u.activo
    AND u.auth_user_id IS NOT NULL
    AND u.rol_id IN (1, 3, 4, 9, 31, 40)  -- Super Admin · Agente Inmobiliario · Inmobiliaria ·
                                          -- Agente Interno · Supervisor externos · Agente Externo
  ORDER BY u.nombre;
$$;

-- ─────────────────────────────────────────────────────────────────────
-- 8. Grants (sin esto el front recibe 403 en .rpc)
-- ─────────────────────────────────────────────────────────────────────
REVOKE ALL ON FUNCTION public.reasignar_lead(bigint, uuid, text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.get_agentes_asignables()           FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.reasignar_lead(bigint, uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_agentes_asignables()           TO authenticated;

-- ─────────────────────────────────────────────────────────────────────
-- 9. Backfill: dueño = creador de su oferta, donde exista.
--    Si ya corrió el backfill 4 del archivo 04, esto no encuentra nada nuevo.
-- ─────────────────────────────────────────────────────────────────────
WITH creador AS (
  SELECT DISTINCT ON (er.id) er.id AS id_er, u.auth_user_id
  FROM public.entidades_relacionadas er
  JOIN public.ofertas o  ON o.id_persona_lead = er.id_persona AND o.activo
  JOIN public.usuarios u ON lower(u.email) = lower(o.email_creador)
                        AND u.auth_user_id IS NOT NULL
  LEFT JOIN public.crm_leads_atribucion a ON a.id_entidad_relacionada = er.id AND a.activo
  WHERE er.activo AND er.id_tipo_entidad = 7
    AND er.id_persona_duena_lead IS NULL
    AND (a.id IS NULL OR a.id_propietario IS NULL)
  ORDER BY er.id, o.fecha_generacion DESC NULLS LAST, o.id DESC
)
INSERT INTO public.crm_leads_atribucion (id_entidad_relacionada, id_propietario, origen, activo)
SELECT c.id_er, c.auth_user_id, 'oferta', true
FROM creador c
ON CONFLICT (id_entidad_relacionada) DO UPDATE
  SET id_propietario = COALESCE(public.crm_leads_atribucion.id_propietario, EXCLUDED.id_propietario);

-- ─────────────────────────────────────────────────────────────────────
-- 10. Self-verifying
-- ─────────────────────────────────────────────────────────────────────
DO $$
BEGIN
  IF to_regclass('public.crm_leads_reasignaciones') IS NULL THEN
    RAISE EXCEPTION 'Falta la bitácora crm_leads_reasignaciones';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_crm_lead_autoasignar') THEN
    RAISE EXCEPTION 'Falta el trigger de alta con dueño automático';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_crm_auditar_cambio_dueno') THEN
    RAISE EXCEPTION 'Falta el trigger de auditoría de cambio de dueño';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_crm_sync_dueno_negocios') THEN
    RAISE EXCEPTION 'Falta el trigger que arrastra los negocios en la reasignación';
  END IF;
  IF to_regprocedure('public.reasignar_lead(bigint,uuid,text)') IS NULL
     OR to_regprocedure('public.get_agentes_asignables()') IS NULL THEN
    RAISE EXCEPTION 'Faltan las RPC de reasignación';
  END IF;
  IF has_table_privilege('anon','public.crm_leads_reasignaciones','SELECT') THEN
    RAISE EXCEPTION 'anon puede leer la bitácora de reasignaciones: revocar';
  END IF;
  IF NOT has_function_privilege('authenticated','public.reasignar_lead(bigint,uuid,text)','EXECUTE') THEN
    RAISE EXCEPTION 'authenticated no puede ejecutar reasignar_lead';
  END IF;
  IF has_function_privilege('anon','public.reasignar_lead(bigint,uuid,text)','EXECUTE') THEN
    RAISE EXCEPTION 'anon puede ejecutar reasignar_lead: revocar';
  END IF;
END $$;

-- PENDIENTE DE NEGOCIO (no lo resuelve este archivo): `NewOfferDialog.tsx` y
-- `NewProductOfferDialog.tsx` reasignan el lead al creador de la oferta, así que generar una
-- oferta sobre un prospecto ajeno se lo queda — contra la regla de «traspaso explícito». Aquí
-- solo queda VISIBLE en la bitácora. Salidas, en orden de preferencia:
--   1. Quitar esos dos UPDATE del front y exigir el traspaso (cambio de dos líneas).
--   2. Que el front llame a reasignar_lead() en vez de escribir la columna: queda con motivo
--      y con validación de permiso.
--   3. Dejarlo: la bitácora al menos permite reconstruir quién le quitó qué a quién.
--
-- Rollback:
--   DROP TRIGGER IF EXISTS trg_crm_lead_autoasignar     ON public.entidades_relacionadas;
--   DROP TRIGGER IF EXISTS trg_crm_auditar_cambio_dueno ON public.entidades_relacionadas;
--   DROP TRIGGER IF EXISTS trg_crm_sync_dueno_negocios  ON public.crm_leads_atribucion;
--   DROP FUNCTION IF EXISTS public.fn_crm_lead_autoasignar();
--   DROP FUNCTION IF EXISTS public.fn_crm_auditar_cambio_dueno();
--   DROP FUNCTION IF EXISTS public.fn_crm_sync_dueno_negocios();
--   DROP FUNCTION IF EXISTS public.reasignar_lead(bigint, uuid, text);
--   DROP FUNCTION IF EXISTS public.get_agentes_asignables();
--   -- La bitácora NO se borra en un rollback ordinario.
