-- Tabla de atribución de leads de Meta (Meta Lead Ads) para el CRM.
-- Los datos de contacto (nombre, email, teléfono) viven en `personas`; la relación
-- prospecto/comprador ↔ proyecto vive en `entidades_relacionadas`. Esta tabla SOLO
-- guarda el estado del lead en el CRM y la atribución de Meta, enlazada por
-- `id_entidad_relacionada`.

-- ─── 1. Tabla principal ───────────────────────────────────────────────────────
CREATE TABLE public.crm_leads_atribucion (
    id                      INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_entidad_relacionada  BIGINT       NOT NULL
        REFERENCES public.entidades_relacionadas(id) ON DELETE CASCADE,

    -- Estado del CRM (nuestro, en español)
    estatus_lead            TEXT         NOT NULL DEFAULT 'nuevo',
    etapa_ciclo_vida        TEXT         NOT NULL DEFAULT 'lead',
    id_propietario          UUID,        -- auth_user_id del asesor asignado

    -- Atribución de Meta Lead Ads (nombres de Meta con prefijo meta_)
    meta_leadgen_id         TEXT,        -- id del lead en Meta
    meta_form_id            TEXT,
    meta_form_name          TEXT,
    meta_page_id            TEXT,
    meta_ad_id              TEXT,
    meta_adgroup_id         TEXT,        -- ad set
    meta_campaign_id        TEXT,
    meta_platform           TEXT,        -- fb, ig
    meta_created_time       TIMESTAMPTZ, -- created_time del lead en Meta
    meta_field_data         JSONB        NOT NULL DEFAULT '[]'::jsonb, -- respuestas crudas del form

    activo                  BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    fecha_actualizacion     TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ─── 2. Índices ───────────────────────────────────────────────────────────────
CREATE INDEX idx_crm_leads_atr_er
    ON public.crm_leads_atribucion (id_entidad_relacionada);

CREATE UNIQUE INDEX idx_crm_leads_atr_leadgen
    ON public.crm_leads_atribucion (meta_leadgen_id)
    WHERE meta_leadgen_id IS NOT NULL;

-- ─── 3. Trigger — fecha_actualizacion automática ─────────────────────────────
CREATE OR REPLACE FUNCTION public.set_crm_leads_atribucion_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.fecha_actualizacion = NOW();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_crm_leads_atribucion_updated_at
BEFORE UPDATE ON public.crm_leads_atribucion
FOR EACH ROW EXECUTE FUNCTION public.set_crm_leads_atribucion_updated_at();

-- ─── 4. Row Level Security ────────────────────────────────────────────────────
ALTER TABLE public.crm_leads_atribucion ENABLE ROW LEVEL SECURITY;

-- Lectura: admins, usuarios con permiso global de prospectos, o el propietario del lead.
CREATE POLICY "crm_leads_atribucion_select"
    ON public.crm_leads_atribucion FOR SELECT
    TO authenticated
    USING (
        is_admin_user()
        OR can_view_all_prospects()
        OR id_propietario = auth.uid()
    );

-- Inserción: cualquier usuario autenticado (ingesta n8n / alta manual).
CREATE POLICY "crm_leads_atribucion_insert"
    ON public.crm_leads_atribucion FOR INSERT
    TO authenticated
    WITH CHECK (true);

-- Modificación: admins, permiso global de prospectos, o el propietario del lead.
CREATE POLICY "crm_leads_atribucion_update"
    ON public.crm_leads_atribucion FOR UPDATE
    TO authenticated
    USING (
        is_admin_user()
        OR can_view_all_prospects()
        OR id_propietario = auth.uid()
    )
    WITH CHECK (
        is_admin_user()
        OR can_view_all_prospects()
        OR id_propietario = auth.uid()
    );

-- Eliminación: solo administradores.
CREATE POLICY "crm_leads_atribucion_delete"
    ON public.crm_leads_atribucion FOR DELETE
    TO authenticated
    USING (is_admin_user());
