-- Notas del CRM: soporte para anclar (pin) y para comentarios.

-- ─── 1. Anclar notas ──────────────────────────────────────────────────────────
ALTER TABLE public.crm_notas
    ADD COLUMN IF NOT EXISTS anclado BOOLEAN NOT NULL DEFAULT FALSE;

-- ─── 2. Comentarios de notas ──────────────────────────────────────────────────
CREATE TABLE public.crm_notas_comentarios (
    id              INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_nota         INTEGER      NOT NULL REFERENCES public.crm_notas(id) ON DELETE CASCADE,
    id_usuario      UUID,        -- auth_user_id del autor del comentario
    contenido       TEXT         NOT NULL,
    activo          BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_crm_notas_comentarios_nota ON public.crm_notas_comentarios (id_nota);

-- ─── 3. Row Level Security ────────────────────────────────────────────────────
ALTER TABLE public.crm_notas_comentarios ENABLE ROW LEVEL SECURITY;

CREATE POLICY "crm_notas_comentarios_select" ON public.crm_notas_comentarios
    FOR SELECT TO authenticated USING (true);
CREATE POLICY "crm_notas_comentarios_insert" ON public.crm_notas_comentarios
    FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "crm_notas_comentarios_update" ON public.crm_notas_comentarios
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "crm_notas_comentarios_delete" ON public.crm_notas_comentarios
    FOR DELETE TO authenticated USING (is_admin_user());
