-- =============================================================================
-- Anexos ("Otros documentos") en el expediente del cliente
-- =============================================================================
-- El expediente de persona moral necesita anexos: reformas y protocolizaciones
-- posteriores al acta constitutiva, y lo que se pida caso por caso. Son varios, no se
-- traslapan, y cada uno necesita decir QUÉ es. Hoy `documentos` no tiene dónde guardar
-- esa descripción.
--
-- Cambio aditivo: una columna nullable y una fila de catálogo. Nada se modifica.
--
-- ─── Verificado read-only el 2026-08-13 en prod (tzmhgfjmddkfyffkkmto) y dev ──
-- · `documentos` NO tiene columna `descripcion` en ninguno de los dos.
-- · `documentos.numero` está ocupado como folio (467 filas de 8456); no sirve de
--   descripción.
-- · `documentos` admite VARIAS filas por persona y tipo: sus únicas restricciones son
--   UNIQUE (url) y chk_doc_url_formato. No hay unique por (id_persona, id_tipo_documento).
--   Por eso las reformas (tipo 57) ya pueden repetirse sin ningún cambio de esquema.
-- · categorias_tipo_documento id 9 = 'Otro' existe en ambos.
-- · tipo 57 'Reformas, modificaciones y protocolizaciones posteriores al acta
--   constitutiva' existe con el MISMO id en dev y prod (asignado_a='per', padre='pm',
--   categoría 5). No se toca.
-- · 'Otros documentos' no existe todavía en ninguno de los dos.
-- · tipos_documento.id es GENERATED BY DEFAULT AS IDENTITY → el INSERT sin id funciona.
-- · tipos_documento tiene UNIQUE (nombre) → el INSERT va con ON CONFLICT para ser
--   idempotente y no tumbar el CI si se reejecuta.
--
-- ─── OJO: el id NO va a ser el mismo en dev y en prod ─────────────────────────
-- max(tipos_documento.id) hoy: prod = 68, dev = 73. Los catálogos ya venían
-- desalineados, así que esta fila nacerá con id 69 en prod y 74 en dev.
--
-- El backend NO debe hardcodear el id. Debe resolverlo por nombre:
--   SELECT id FROM tipos_documento WHERE nombre = 'Otros documentos'
-- o exponerlo por catálogo. Si se clava un número, se rompe en uno de los dos entornos.
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- §1. Descripción del documento
-- -----------------------------------------------------------------------------
-- Nullable y aditiva: ninguna de las 8456 filas existentes cambia y ningún consumidor
-- se rompe. Es lo que el cliente escribe para distinguir un anexo de otro
-- ("Reforma de estatutos 2024", "Cambio de domicilio social").
ALTER TABLE public.documentos
  ADD COLUMN IF NOT EXISTS descripcion text;

COMMENT ON COLUMN public.documentos.descripcion IS
  'Texto libre que distingue un anexo de otro dentro del mismo tipo de documento '
  '(p. ej. "Reforma de estatutos 2024"). Lo captura quien sube el archivo. '
  'No confundir con `numero`, que es el folio del documento.';

-- -----------------------------------------------------------------------------
-- §2. Tipo de documento para los anexos libres
-- -----------------------------------------------------------------------------
-- Guard: la categoría 9 tiene que ser la de "Otro". El FK solo garantiza que exista;
-- esto verifica que sea la que se quiso usar y no otra renumerada.
DO $guard$
DECLARE
  v_nombre text;
BEGIN
  SELECT nombre INTO v_nombre FROM public.categorias_tipo_documento WHERE id = 9;

  IF v_nombre IS NULL THEN
    RAISE EXCEPTION 'No existe categorias_tipo_documento id 9; revisar el catálogo antes de crear el tipo';
  END IF;

  IF lower(btrim(v_nombre)) <> 'otro' THEN
    RAISE EXCEPTION 'categorias_tipo_documento id 9 es "%", se esperaba "Otro"; el catálogo se renumeró', v_nombre;
  END IF;
END;
$guard$;

-- asignado_a = 'per': es documento de PERSONA. Los demás tipos de la categoría 9 son de
--   propiedad y juicios ('prop'), por eso no sirven tal cual.
-- padre = 'a': aplica a los dos tipos de persona, moral y física; los anexos se piden a
--   ambas. Ya hay 33 tipos con padre='a', no hay CHECK que lo restrinja.
INSERT INTO public.tipos_documento
  (nombre, activo, padre, id_categoria_documento, asignado_a)
VALUES
  ('Otros documentos', true, 'a', 9, 'per')
ON CONFLICT (nombre) DO NOTHING;

-- Deja el id en el log del deploy, porque no es el mismo en dev que en prod.
DO $log$
DECLARE
  v_id integer;
BEGIN
  SELECT id INTO v_id FROM public.tipos_documento WHERE nombre = 'Otros documentos';

  IF v_id IS NULL THEN
    RAISE EXCEPTION 'No quedó registrado el tipo "Otros documentos"';
  END IF;

  RAISE NOTICE 'tipos_documento "Otros documentos" → id %. El backend debe resolverlo por nombre, no clavarlo.', v_id;
END;
$log$;

COMMIT;

-- =============================================================================
-- Verificación (read-only, correr después del deploy)
-- =============================================================================
-- SELECT column_name, data_type, is_nullable
-- FROM information_schema.columns
-- WHERE table_schema = 'public' AND table_name = 'documentos' AND column_name = 'descripcion';
--
-- SELECT id, nombre, activo, padre, asignado_a, id_categoria_documento
-- FROM public.tipos_documento
-- WHERE nombre = 'Otros documentos';
--
-- -- Que sigan admitiéndose varias filas por persona y tipo (esperado: sin unique):
-- SELECT conname, pg_get_constraintdef(oid)
-- FROM pg_constraint
-- WHERE conrelid = 'public.documentos'::regclass AND contype = 'u';
-- =============================================================================
