-- Modelo de datos del módulo "Portal Tickets de Seguimiento" (tickets estilo HubSpot).
--
-- Contexto (junta 2026-07-29, Manuel / Sergio): se necesita un sistema de tickets de
-- propósito general (escrituración, servicio al cliente, entregas, mantenimiento) con
-- pipeline + etapas configurables, asignación a un responsable, enlace al contacto del CRM
-- y al inmueble, y timeline de actividad. La UI ya existe (generada por Lovable) pero opera
-- 100% con datos mock en memoria; estas tablas le dan persistencia real. El menú, submenús y
-- permisos ya se sembraron en 20260731000000_portal_tickets_seguimiento_menu_permisos.sql.
--
-- Nomenclatura: el módulo vive FUERA del CRM (portal propio /admin/portal-tickets), por eso las
-- tablas usan el prefijo de módulo `tickets_` (no `crm_`). Tabla central: `tickets`.
--
-- Decisiones de modelado:
--   * Familia propia `tickets_*`. NO se reutiliza crm_pipelines/crm_negocios: las etapas de
--     ventas usan probabilidad/es_ganado/es_perdido, las de tickets usan `cerrada`. Tampoco se
--     reutiliza postventa_tickets, que es de garantías/SLA técnico (otro propósito).
--   * Mismas convenciones que el resto del sistema: id INTEGER GENERATED BY DEFAULT AS IDENTITY,
--     activo, fecha_creacion/fecha_actualizacion con trigger, RLS authenticated + delete is_admin_user().
--   * Enlace al CRM: id_entidad_relacionada -> entidades_relacionadas (contacto/solicitante) e
--     id_propiedad -> propiedades (inmueble). Se conservan `solicitante`/`inmueble` como texto de
--     respaldo por si el reporte no corresponde a un contacto/propiedad registrado.
--   * Asignación: id_usuario_propietario (auth_user_id, igual que crm_negocios). NULL = sin asignar.
--   * Estado abierto/cerrado es DERIVADO de la etapa (tickets_etapas.cerrada) + fecha_cierre;
--     no hay columna de estado redundante.
--   * Prioridad = enum fijo (la UI la trata como catálogo inmutable).
--   * Folio visible = secuencia tickets_numero_seq (arranca en 1000).
--
-- Idempotente (IF NOT EXISTS / guards / NOT EXISTS en seed). Arranca limpio: 0 tickets, solo
-- catálogos semilla. Sin BEGIN/COMMIT (el CI/CD lo envuelve en transacción). Corre en Preview y
-- Producción.

-- ─── Enum de prioridad ────────────────────────────────────────────────────────
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tickets_prioridad') THEN
    CREATE TYPE public.tickets_prioridad AS ENUM ('alta', 'media', 'baja', 'sin');
  END IF;
END;
$$;

-- ─── tickets_pipelines ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.tickets_pipelines (
    id                   INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre               TEXT         NOT NULL,
    descripcion          TEXT,
    orden                INTEGER      NOT NULL DEFAULT 100,
    activo               BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    fecha_actualizacion  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ─── tickets_etapas ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.tickets_etapas (
    id                   INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pipeline          INTEGER      NOT NULL
        REFERENCES public.tickets_pipelines(id) ON DELETE CASCADE,
    nombre               TEXT         NOT NULL,
    orden                INTEGER      NOT NULL DEFAULT 100,
    cerrada              BOOLEAN      NOT NULL DEFAULT FALSE,  -- etapa terminal -> setea fecha_cierre
    activo               BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    fecha_actualizacion  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tickets_etapas_pipeline ON public.tickets_etapas (id_pipeline);

-- ─── tickets_categorias ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.tickets_categorias (
    id                   INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre               TEXT         NOT NULL,
    orden                INTEGER      NOT NULL DEFAULT 100,
    activo               BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    fecha_actualizacion  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ─── Secuencia de folio visible ───────────────────────────────────────────────
CREATE SEQUENCE IF NOT EXISTS public.tickets_numero_seq START WITH 1000 INCREMENT BY 1;

-- ─── tickets (entidad central) ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.tickets (
    id                      INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero                  INTEGER      NOT NULL DEFAULT nextval('public.tickets_numero_seq'),  -- folio visible
    nombre                  TEXT         NOT NULL,                 -- asunto del ticket
    id_pipeline             INTEGER      NOT NULL REFERENCES public.tickets_pipelines(id),
    id_etapa                INTEGER      NOT NULL REFERENCES public.tickets_etapas(id),
    prioridad               public.tickets_prioridad NOT NULL DEFAULT 'sin',
    id_categoria            INTEGER      REFERENCES public.tickets_categorias(id) ON DELETE SET NULL,
    id_usuario_propietario  UUID,                                 -- auth_user_id del asignado; NULL = sin asignar
    id_usuario_creador      UUID,                                 -- auth_user_id de quien lo creó
    id_entidad_relacionada  BIGINT       REFERENCES public.entidades_relacionadas(id) ON DELETE SET NULL, -- contacto CRM
    id_propiedad            BIGINT       REFERENCES public.propiedades(id) ON DELETE SET NULL,             -- inmueble
    solicitante             TEXT,                                 -- respaldo texto si no es contacto registrado
    inmueble                TEXT,                                 -- respaldo texto si no es propiedad registrada
    descripcion             TEXT,
    fuente                  TEXT         NOT NULL DEFAULT 'Portal',
    fecha_creacion          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    fecha_cierre            TIMESTAMPTZ,                           -- se setea al mover a etapa cerrada
    activo                  BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_actualizacion     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_tickets_numero UNIQUE (numero)
);

ALTER SEQUENCE public.tickets_numero_seq OWNED BY public.tickets.numero;

CREATE INDEX IF NOT EXISTS idx_tickets_pipeline    ON public.tickets (id_pipeline);
CREATE INDEX IF NOT EXISTS idx_tickets_etapa       ON public.tickets (id_etapa);
CREATE INDEX IF NOT EXISTS idx_tickets_categoria   ON public.tickets (id_categoria);
CREATE INDEX IF NOT EXISTS idx_tickets_propietario ON public.tickets (id_usuario_propietario);
CREATE INDEX IF NOT EXISTS idx_tickets_er          ON public.tickets (id_entidad_relacionada);
CREATE INDEX IF NOT EXISTS idx_tickets_propiedad   ON public.tickets (id_propiedad);
CREATE INDEX IF NOT EXISTS idx_tickets_activo      ON public.tickets (activo);

-- ─── tickets_actividad (timeline: eventos de sistema y notas) ──────────────────
CREATE TABLE IF NOT EXISTS public.tickets_actividad (
    id                 INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ticket          INTEGER      NOT NULL REFERENCES public.tickets(id) ON DELETE CASCADE,
    tipo               TEXT         NOT NULL DEFAULT 'sistema',  -- 'sistema' | 'nota' | 'cambio_estado' | 'asignacion'
    texto              TEXT         NOT NULL,
    id_usuario_autor   UUID,                                    -- auth_user_id; NULL = evento del sistema
    fecha_creacion     TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tickets_actividad_ticket ON public.tickets_actividad (id_ticket);

-- ─── Trigger fecha_actualizacion automática ───────────────────────────────────
CREATE OR REPLACE FUNCTION public.tickets_set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.fecha_actualizacion = NOW();
    RETURN NEW;
END;
$$;

DO $$
DECLARE
    t TEXT;
BEGIN
    FOREACH t IN ARRAY ARRAY['tickets_pipelines','tickets_etapas','tickets_categorias','tickets']
    LOOP
        EXECUTE format('DROP TRIGGER IF EXISTS %I ON public.%I', 'trg_' || t || '_updated_at', t);
        EXECUTE format(
            'CREATE TRIGGER %I BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.tickets_set_updated_at()',
            'trg_' || t || '_updated_at', t
        );
    END LOOP;
END;
$$;

-- ─── Row Level Security ───────────────────────────────────────────────────────
-- Igual que la familia crm_negocios: lectura/escritura para autenticados, borrado admin.
ALTER TABLE public.tickets_pipelines   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tickets_etapas      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tickets_categorias  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tickets             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tickets_actividad   ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
    t TEXT;
BEGIN
    FOREACH t IN ARRAY ARRAY['tickets_pipelines','tickets_etapas','tickets_categorias','tickets','tickets_actividad']
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', t || '_select', t);
        EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', t || '_insert', t);
        EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', t || '_update', t);
        EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', t || '_delete', t);

        EXECUTE format('CREATE POLICY %I ON public.%I FOR SELECT TO authenticated USING (true)', t || '_select', t);
        EXECUTE format('CREATE POLICY %I ON public.%I FOR INSERT TO authenticated WITH CHECK (true)', t || '_insert', t);
        EXECUTE format('CREATE POLICY %I ON public.%I FOR UPDATE TO authenticated USING (true) WITH CHECK (true)', t || '_update', t);
        EXECUTE format('CREATE POLICY %I ON public.%I FOR DELETE TO authenticated USING (is_admin_user())', t || '_delete', t);
    END LOOP;
END;
$$;

-- ─── Seed idempotente: catálogos base (arranque limpio, sin tickets) ───────────
-- Pipelines
INSERT INTO public.tickets_pipelines (nombre, descripcion, orden, activo)
SELECT v.nombre, v.descripcion, v.orden, TRUE
FROM (VALUES
    ('Atención al Cliente',   'Reportes de residentes y clientes finales',               10),
    ('Mantenimiento Interno', 'Órdenes de trabajo generadas por el equipo de operación',  20)
) AS v(nombre, descripcion, orden)
WHERE NOT EXISTS (
    SELECT 1 FROM public.tickets_pipelines p WHERE p.nombre = v.nombre
);

-- Etapas del pipeline "Atención al Cliente"
INSERT INTO public.tickets_etapas (id_pipeline, nombre, orden, cerrada, activo)
SELECT p.id, v.nombre, v.orden, v.cerrada, TRUE
FROM public.tickets_pipelines p
CROSS JOIN (VALUES
    ('Nuevo',                  10, FALSE),
    ('Asignado para atención', 20, FALSE),
    ('En revisión',            30, FALSE),
    ('Cerrado',                40, TRUE)
) AS v(nombre, orden, cerrada)
WHERE p.nombre = 'Atención al Cliente'
  AND NOT EXISTS (
    SELECT 1 FROM public.tickets_etapas e WHERE e.id_pipeline = p.id AND e.nombre = v.nombre
  );

-- Etapas del pipeline "Mantenimiento Interno"
INSERT INTO public.tickets_etapas (id_pipeline, nombre, orden, cerrada, activo)
SELECT p.id, v.nombre, v.orden, v.cerrada, TRUE
FROM public.tickets_pipelines p
CROSS JOIN (VALUES
    ('Solicitud',    10, FALSE),
    ('Programado',   20, FALSE),
    ('En ejecución', 30, FALSE),
    ('Cerrado',      40, TRUE)
) AS v(nombre, orden, cerrada)
WHERE p.nombre = 'Mantenimiento Interno'
  AND NOT EXISTS (
    SELECT 1 FROM public.tickets_etapas e WHERE e.id_pipeline = p.id AND e.nombre = v.nombre
  );

-- Categorías
INSERT INTO public.tickets_categorias (nombre, orden, activo)
SELECT v.nombre, v.orden, TRUE
FROM (VALUES
    ('Calentador Eléctrico',        10),
    ('Carpintería',                 20),
    ('Agua y drenaje',              30),
    ('Desperfecto Infraestructura', 40),
    ('Electricidad',                50),
    ('Plomería',                    60),
    ('Pintura y acabados',          70),
    ('Cerrajería',                  80),
    ('Jardinería y áreas comunes',  90),
    ('Limpieza',                    100)
) AS v(nombre, orden)
WHERE NOT EXISTS (
    SELECT 1 FROM public.tickets_categorias c WHERE c.nombre = v.nombre
);
