-- Categorías de contacto del CRM (procedencia). Catálogo PROPIO del CRM para NO
-- mezclar con `tipos_entidad` (estructural del sistema, usado en muchas partes).
-- Un contacto (= fila de `entidades_relacionadas`, prospecto tipo 7 / comprador
-- tipo 2) puede tener VARIAS categorías -> tabla puente M:N.

-- ─── Catálogo crm_categorias ──────────────────────────────────────────────────
CREATE TABLE public.crm_categorias (
    id              INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          TEXT         NOT NULL UNIQUE,
    descripcion     TEXT,
    orden           INTEGER      NOT NULL DEFAULT 100,
    activo          BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- Categorías iniciales confirmadas por Abel/Ramón (2026-07-17).
INSERT INTO public.crm_categorias (nombre, orden) VALUES
    ('Lead Interno',   10),
    ('Lead Externo',   20),
    ('Agente Externo', 30),
    ('Embajador',      40),
    ('Socio',          50),
    ('Proveedor',      60),
    ('Colaborador',    70);

-- ─── Puente M:N entidades_relacionadas <-> crm_categorias ─────────────────────
CREATE TABLE public.entidades_relacionadas_categorias (
    id                      INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_entidad_relacionada  BIGINT       NOT NULL
        REFERENCES public.entidades_relacionadas(id) ON DELETE CASCADE,
    id_categoria            INTEGER      NOT NULL
        REFERENCES public.crm_categorias(id) ON DELETE CASCADE,
    activo                  BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    UNIQUE (id_entidad_relacionada, id_categoria)
);

CREATE INDEX idx_er_categorias_er  ON public.entidades_relacionadas_categorias (id_entidad_relacionada);
CREATE INDEX idx_er_categorias_cat ON public.entidades_relacionadas_categorias (id_categoria);

-- ─── Row Level Security ───────────────────────────────────────────────────────
-- Catálogo: todos leen; solo admin administra. Puente: authenticated lee/escribe
-- (para que un asesor etiquete), borrado duro solo admin (el front usa soft-delete
-- vía activo=false, que cae en UPDATE y sí lo puede hacer el asesor).
ALTER TABLE public.crm_categorias                    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.entidades_relacionadas_categorias ENABLE ROW LEVEL SECURITY;

CREATE POLICY "crm_categorias_select" ON public.crm_categorias
    FOR SELECT TO authenticated USING (true);
CREATE POLICY "crm_categorias_insert" ON public.crm_categorias
    FOR INSERT TO authenticated WITH CHECK (is_admin_user());
CREATE POLICY "crm_categorias_update" ON public.crm_categorias
    FOR UPDATE TO authenticated USING (is_admin_user()) WITH CHECK (is_admin_user());
CREATE POLICY "crm_categorias_delete" ON public.crm_categorias
    FOR DELETE TO authenticated USING (is_admin_user());

CREATE POLICY "er_categorias_select" ON public.entidades_relacionadas_categorias
    FOR SELECT TO authenticated USING (true);
CREATE POLICY "er_categorias_insert" ON public.entidades_relacionadas_categorias
    FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "er_categorias_update" ON public.entidades_relacionadas_categorias
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "er_categorias_delete" ON public.entidades_relacionadas_categorias
    FOR DELETE TO authenticated USING (is_admin_user());
