-- Portal Tickets de Seguimiento — multi-propietario (varios responsables por ticket).
--
-- Hasta ahora un ticket tenía UN propietario (tickets.id_usuario_propietario UUID). El negocio
-- pide que pueda tener VARIOS. Se crea la tabla de unión tickets_propietarios (N a N
-- ticket ↔ usuario) y se migran los propietarios actuales. La columna
-- tickets.id_usuario_propietario se conserva (legacy) pero el front pasa a usar esta tabla.
--
-- La relación se maneja por presencia de fila (INSERT al asignar, DELETE al desasignar), por eso
-- no lleva columna `activo`. Idempotente. Sin BEGIN/COMMIT. Corre en Preview y Producción.

CREATE TABLE IF NOT EXISTS public.tickets_propietarios (
    id              INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ticket       INTEGER      NOT NULL REFERENCES public.tickets(id) ON DELETE CASCADE,
    id_usuario      UUID         NOT NULL,   -- auth_user_id del propietario
    fecha_creacion  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_tickets_propietarios UNIQUE (id_ticket, id_usuario)
);

CREATE INDEX IF NOT EXISTS idx_tickets_propietarios_ticket  ON public.tickets_propietarios (id_ticket);
CREATE INDEX IF NOT EXISTS idx_tickets_propietarios_usuario ON public.tickets_propietarios (id_usuario);

-- RLS: lectura/escritura para autenticados (gestionar asignaciones es operación normal del portal).
ALTER TABLE public.tickets_propietarios ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
    DROP POLICY IF EXISTS tickets_propietarios_select ON public.tickets_propietarios;
    DROP POLICY IF EXISTS tickets_propietarios_insert ON public.tickets_propietarios;
    DROP POLICY IF EXISTS tickets_propietarios_delete ON public.tickets_propietarios;
    CREATE POLICY tickets_propietarios_select ON public.tickets_propietarios
        FOR SELECT TO authenticated USING (true);
    CREATE POLICY tickets_propietarios_insert ON public.tickets_propietarios
        FOR INSERT TO authenticated WITH CHECK (true);
    CREATE POLICY tickets_propietarios_delete ON public.tickets_propietarios
        FOR DELETE TO authenticated USING (true);
END;
$$;

-- Migrar los propietarios actuales (un solo dueño) a la tabla de unión.
INSERT INTO public.tickets_propietarios (id_ticket, id_usuario)
SELECT t.id, t.id_usuario_propietario
FROM public.tickets t
WHERE t.id_usuario_propietario IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM public.tickets_propietarios tp
    WHERE tp.id_ticket = t.id AND tp.id_usuario = t.id_usuario_propietario
  );
