-- CRUD de estados de lead del CRM. Hasta ahora los estados eran un array fijo en el
-- front (META_LEAD_STATUSES). Se vuelven configurables: catálogo en BD con color y
-- orden editables. `crm_leads_atribucion.estatus_lead` (TEXT) sigue guardando la `clave`.
-- Idempotente y self-guarded. El submenú se crea resolviendo el menú CRM ACTIVO desde un
-- submenú hermano existente (robusto dev/prod, sin ids fijos). Los ROLES que ven la
-- pantalla se asignan desde Roles y Permisos (UI), NO aquí.

-- ─── Catálogo crm_estados_lead ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.crm_estados_lead (
    id                   INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clave                TEXT         NOT NULL UNIQUE,            -- valor en crm_leads_atribucion.estatus_lead
    nombre               TEXT         NOT NULL,                   -- etiqueta visible
    color                TEXT         NOT NULL DEFAULT '#64748b', -- hex para el badge
    orden                INTEGER      NOT NULL DEFAULT 100,
    activo               BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    fecha_actualizacion  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_crm_estados_lead_orden ON public.crm_estados_lead (orden);

-- Trigger fecha_actualizacion (reusa la función compartida de 20260721080000).
DROP TRIGGER IF EXISTS trg_crm_estados_lead_fecha_actualizacion ON public.crm_estados_lead;
CREATE TRIGGER trg_crm_estados_lead_fecha_actualizacion
BEFORE UPDATE ON public.crm_estados_lead
FOR EACH ROW EXECUTE FUNCTION public.crm_set_fecha_actualizacion();

-- ─── RLS (espejo de crm_pipelines) ────────────────────────────────────────────
ALTER TABLE public.crm_estados_lead ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "crm_estados_lead_select" ON public.crm_estados_lead;
CREATE POLICY "crm_estados_lead_select" ON public.crm_estados_lead
    FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "crm_estados_lead_insert" ON public.crm_estados_lead;
CREATE POLICY "crm_estados_lead_insert" ON public.crm_estados_lead
    FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "crm_estados_lead_update" ON public.crm_estados_lead;
CREATE POLICY "crm_estados_lead_update" ON public.crm_estados_lead
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "crm_estados_lead_delete" ON public.crm_estados_lead;
CREATE POLICY "crm_estados_lead_delete" ON public.crm_estados_lead
    FOR DELETE TO authenticated USING (is_admin_user());

-- ─── Seed: los estados que ya existían en el front (idempotente por clave) ─────
INSERT INTO public.crm_estados_lead (clave, nombre, color, orden) VALUES
    ('nuevo',               'Nuevo',                '#0ea5e9',  10),
    ('en_curso',            'En curso',             '#f59e0b',  20),
    ('negocio_abierto',     'Negocio abierto',      '#10b981',  30),
    ('sin_calificar',       'Sin calificar',        '#64748b',  40),
    ('intento_contacto',    'Intento de contacto',  '#f97316',  50),
    ('conectado',           'Conectado',            '#6366f1',  60),
    ('programo_cita',       'Programó cita',        '#14b8a6',  70),
    ('asistio_cita',        'Asistió a cita',       '#22c55e',  80),
    ('fuera_presupuesto',   'Fuera de presupuesto', '#ef4444',  90),
    ('compra_futura',       'Compra futura',        '#8b5cf6', 100),
    ('sin_respuesta_7',     'Sin respuesta 7+',     '#f43f5e', 110),
    ('tiempo_entrega',      'Tiempo de entrega',    '#3b82f6', 120),
    ('asesor_inmobiliario', 'Asesor inmobiliario',  '#0891b2', 130),
    ('registro_error',      'Registro por error',   '#dc2626', 140),
    ('proveedor',           'Proveedor',            '#9333ea', 150),
    ('fuera_area',          'Fuera del área',       '#ea580c', 160)
ON CONFLICT (clave) DO NOTHING;

-- ─── Submenú Configuración › Estados de lead ──────────────────────────────────
-- menu_id se deriva del submenú hermano "Pipelines" (misma sección, menú activo) para
-- no hardcodear ids que difieren entre dev y prod. IDENTITY asigna el id del submenú.
INSERT INTO public.submenus (menu_id, nombre, vista_front_end, orden, activo, solo_usuarioa)
SELECT sib.menu_id, 'Estados de lead', '/admin/portal-crm/configuracion/estados-lead', 682, true, false
FROM (
    SELECT s2.menu_id
    FROM public.submenus s2
    JOIN public.menus m2 ON m2.id = s2.menu_id
    WHERE s2.vista_front_end = '/admin/portal-crm/configuracion/pipelines'
      AND s2.activo = true AND m2.activo = true
    LIMIT 1
) sib
WHERE NOT EXISTS (
    SELECT 1 FROM public.submenus s
    WHERE s.vista_front_end = '/admin/portal-crm/configuracion/estados-lead'
      AND s.menu_id = sib.menu_id);

-- Permisos DISPONIBLES del submenú (catálogo de acciones: leer/crear/actualizar/eliminar).
INSERT INTO public.submenus_permisos_disponibles (submenu_id, permiso_id, activo)
SELECT s.id, p.permiso_id, true
FROM public.submenus s
JOIN public.menus m ON m.id = s.menu_id
CROSS JOIN (VALUES (1), (2), (3), (4)) AS p(permiso_id)
WHERE s.vista_front_end = '/admin/portal-crm/configuracion/estados-lead'
  AND s.activo = true AND m.activo = true
  AND NOT EXISTS (
      SELECT 1 FROM public.submenus_permisos_disponibles d
      WHERE d.submenu_id = s.id AND d.permiso_id = p.permiso_id);
