-- Adjuntos de las notas del CRM: imágenes (incl. pegadas con Ctrl+V), archivos y
-- notas de voz. Una nota (fila de `crm_notas`) puede tener N adjuntos. El binario
-- vive en Storage (bucket `public`, prefijo `crm-notes/`); aquí solo la referencia.
-- RLS espejo de `crm_notas` / `crm_notas_comentarios`: authenticated lee/crea/actualiza
-- (soft-delete vía activo=false), borrado duro solo admin.
-- Idempotente y self-guarded para no romper el CI si se re-corre.

CREATE TABLE IF NOT EXISTS public.crm_notas_adjuntos (
    id              INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_nota         INTEGER      NOT NULL
        REFERENCES public.crm_notas(id) ON DELETE CASCADE,
    tipo            TEXT         NOT NULL
        CHECK (tipo IN ('image', 'file', 'audio')),
    url             TEXT         NOT NULL,
    nombre          TEXT         NOT NULL,
    mime            TEXT,
    tamano_bytes    BIGINT,
    id_usuario      UUID,
    activo          BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_crm_notas_adjuntos_nota
    ON public.crm_notas_adjuntos (id_nota);

-- ─── Row Level Security ───────────────────────────────────────────────────────
ALTER TABLE public.crm_notas_adjuntos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "crm_notas_adjuntos_select" ON public.crm_notas_adjuntos;
CREATE POLICY "crm_notas_adjuntos_select" ON public.crm_notas_adjuntos
    FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "crm_notas_adjuntos_insert" ON public.crm_notas_adjuntos;
CREATE POLICY "crm_notas_adjuntos_insert" ON public.crm_notas_adjuntos
    FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "crm_notas_adjuntos_update" ON public.crm_notas_adjuntos;
CREATE POLICY "crm_notas_adjuntos_update" ON public.crm_notas_adjuntos
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "crm_notas_adjuntos_delete" ON public.crm_notas_adjuntos;
CREATE POLICY "crm_notas_adjuntos_delete" ON public.crm_notas_adjuntos
    FOR DELETE TO authenticated USING (is_admin_user());
