-- 20260817180000_facturas_mantenimientos_homologar_prod.sql
-- Propósito: alinear la definición de public.facturas_mantenimientos con la que ya está
-- viva en producción. La tabla se creó en 20260625020000 y después fue alterada
-- directamente en prod, sin migración: el repositorio y Preview quedaron describiendo una
-- estructura que producción dejó de tener. Esta migración cierra ese drift tomando prod
-- como fuente de la verdad (decisión de Jorge, 2026-08-17).
--
-- Estado verificado en prod el 2026-08-17 (pg_dump --schema-only):
--
--   id                   integer NOT NULL  -- GENERATED BY DEFAULT AS IDENTITY
--   id_pago              integer           -- NULLABLE, sin UNIQUE
--   facturado            boolean NOT NULL DEFAULT false
--   url_factura_pdf      text
--   url_factura_xml      text
--   fecha_creacion       timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
--   fecha_actualizacion  timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
--   monto                numeric NOT NULL
--   id_cuenta_cobranza   bigint            -- sin FK en prod
--
--   PK (id) · FK id_pago -> pagos(id) · trigger update_updated_at_column
--   RLS habilitada + policy facturas_mantenimientos_rls_auth (ya idéntica en Preview)
--
-- Cuatro diferencias contra lo que describe el repo:
--
--   1. UNIQUE (id_pago) no existe en prod. Es deliberado: prod guarda el PDF y el XML de
--      una misma factura en FILAS SEPARADAS con el mismo id_pago (92 filas = 46 pagos x 2,
--      verificado y documentado en 20260807000000_vistas_facturas_app_cliente.sql). Con el
--      UNIQUE puesto, esos datos no son representables.
--   2. id_pago es NULLABLE en prod, coherente con filas que cuelgan de una cuenta de
--      cobranza en lugar de un pago concreto.
--   3. monto — numeric NOT NULL. En prod coincide con pagos.monto en las 92 filas.
--   4. id_cuenta_cobranza — bigint sin FK. Se replica tal cual, SIN agregar la FK que prod
--      no tiene, para que esta migración sea exactamente un no-op al aplicarse allá.
--
-- NOTA para quien lea esto después: quitar el UNIQUE consolida el modelo de dos filas por
-- factura. Si en algún momento se decide que lo correcto es una fila por pago con dos
-- columnas de URL, esta migración es el punto de partida a revertir, y habrá que
-- consolidar las 92 filas antes de reponer la restricción.

BEGIN;

-- 1. El UNIQUE que prod no tiene.
ALTER TABLE public.facturas_mantenimientos
  DROP CONSTRAINT IF EXISTS facturas_mantenimientos_id_pago_key;

-- 2. id_pago nullable. Idempotente: no-op si ya lo es.
ALTER TABLE public.facturas_mantenimientos
  ALTER COLUMN id_pago DROP NOT NULL;

-- 3 y 4. Columnas ausentes. Se agregan nullable primero para que la migración corra
-- también en entornos con filas previas.
ALTER TABLE public.facturas_mantenimientos
  ADD COLUMN IF NOT EXISTS monto numeric;

ALTER TABLE public.facturas_mantenimientos
  ADD COLUMN IF NOT EXISTS id_cuenta_cobranza bigint;

-- monto es NOT NULL en prod. Solo se impone si ninguna fila lo tiene en NULL; de lo
-- contrario la migración avisa y deja la columna nullable en lugar de abortar el deploy.
DO $$
DECLARE nulos bigint;
BEGIN
  SELECT count(*) INTO nulos
  FROM public.facturas_mantenimientos
  WHERE monto IS NULL;

  IF nulos = 0 THEN
    ALTER TABLE public.facturas_mantenimientos
      ALTER COLUMN monto SET NOT NULL;
  ELSE
    RAISE WARNING
      'facturas_mantenimientos.monto tiene % fila(s) en NULL: se deja nullable. Rellenar y ejecutar ALTER COLUMN monto SET NOT NULL.',
      nulos;
  END IF;
END $$;

COMMENT ON COLUMN public.facturas_mantenimientos.monto IS
  'Monto facturado. Coincide con pagos.monto cuando la fila cuelga de un pago.';

COMMENT ON COLUMN public.facturas_mantenimientos.id_cuenta_cobranza IS
  'Cuenta de cobranza asociada. Sin FK, replicando la definición viva en producción.';

COMMIT;
