-- Comentarios de tarea (estilo HubSpot) — espejo de crm_notas_comentarios pero por TAREA.
-- Hilo simple de texto: cada usuario comenta en una tarea; se muestra en el card/modal de la tarea.
-- Idempotente (IF NOT EXISTS / DROP POLICY IF EXISTS). Sin BEGIN/COMMIT (supabase db push envuelve la tx).

CREATE TABLE IF NOT EXISTS public.crm_tareas_comentarios (
  id                   integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_tarea             integer     NOT NULL REFERENCES public.crm_tareas(id) ON DELETE CASCADE,
  id_usuario           uuid,
  contenido            text        NOT NULL,
  activo               boolean     NOT NULL DEFAULT true,
  fecha_creacion       timestamptz NOT NULL DEFAULT now(),
  fecha_actualizacion  timestamptz NOT NULL DEFAULT now()
);

-- Índice para traer los comentarios activos de una tarea.
CREATE INDEX IF NOT EXISTS idx_crm_tareas_comentarios_tarea
  ON public.crm_tareas_comentarios (id_tarea) WHERE activo;

-- fecha_actualizacion automática (misma función compartida que el resto del CRM).
DROP TRIGGER IF EXISTS trg_crm_tareas_comentarios_fecha_actualizacion ON public.crm_tareas_comentarios;
CREATE TRIGGER trg_crm_tareas_comentarios_fecha_actualizacion
  BEFORE UPDATE ON public.crm_tareas_comentarios
  FOR EACH ROW EXECUTE FUNCTION public.set_fecha_actualizacion();

-- RLS (espejo de crm_notas_comentarios): todos los autenticados LEEN; crear/editar requiere sesión;
-- borrar solo admin.
ALTER TABLE public.crm_tareas_comentarios ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS crm_tareas_comentarios_select ON public.crm_tareas_comentarios;
CREATE POLICY crm_tareas_comentarios_select ON public.crm_tareas_comentarios
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS crm_tareas_comentarios_insert ON public.crm_tareas_comentarios;
CREATE POLICY crm_tareas_comentarios_insert ON public.crm_tareas_comentarios
  FOR INSERT TO authenticated WITH CHECK ((SELECT auth.uid()) IS NOT NULL);

DROP POLICY IF EXISTS crm_tareas_comentarios_update ON public.crm_tareas_comentarios;
CREATE POLICY crm_tareas_comentarios_update ON public.crm_tareas_comentarios
  FOR UPDATE TO authenticated
  USING ((SELECT auth.uid()) IS NOT NULL)
  WITH CHECK ((SELECT auth.uid()) IS NOT NULL);

DROP POLICY IF EXISTS crm_tareas_comentarios_delete ON public.crm_tareas_comentarios;
CREATE POLICY crm_tareas_comentarios_delete ON public.crm_tareas_comentarios
  FOR DELETE TO authenticated USING (public.is_admin_user());

GRANT SELECT, INSERT, UPDATE, DELETE ON public.crm_tareas_comentarios TO authenticated;
