-- Portal Tickets de Seguimiento — múltiples solicitantes (varios contactos por ticket).
--
-- Hasta ahora un ticket tenía UN solicitante: tickets.id_entidad_relacionada (BIGINT → contacto CRM
-- en entidades_relacionadas) + tickets.solicitante (TEXT de respaldo). El negocio pide que un
-- ticket pueda tener VARIOS solicitantes (p.ej. varios afectados por el mismo caso). Se crea la
-- tabla de unión tickets_solicitantes (N a N ticket ↔ entidad_relacionada), espejando
-- tickets_propietarios, y se migran los solicitantes actuales. Las columnas
-- tickets.id_entidad_relacionada y tickets.solicitante se conservan (legacy / "solicitante
-- principal") pero el front pasa a usar esta tabla.
--
-- La relación se maneja por presencia de fila (INSERT al agregar, DELETE al quitar), por eso no
-- lleva columna `activo`. Idempotente. Sin BEGIN/COMMIT (el CI/CD lo envuelve en transacción).
-- Corre en Preview y Producción.

CREATE TABLE IF NOT EXISTS public.tickets_solicitantes (
    id                      INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ticket               INTEGER      NOT NULL REFERENCES public.tickets(id) ON DELETE CASCADE,
    id_entidad_relacionada  BIGINT       NOT NULL REFERENCES public.entidades_relacionadas(id) ON DELETE CASCADE,  -- contacto CRM
    fecha_creacion          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_tickets_solicitantes UNIQUE (id_ticket, id_entidad_relacionada)
);

CREATE INDEX IF NOT EXISTS idx_tickets_solicitantes_ticket   ON public.tickets_solicitantes (id_ticket);
CREATE INDEX IF NOT EXISTS idx_tickets_solicitantes_contacto ON public.tickets_solicitantes (id_entidad_relacionada);

-- RLS: lectura/escritura para autenticados (gestionar solicitantes es operación normal del portal).
ALTER TABLE public.tickets_solicitantes ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
    DROP POLICY IF EXISTS tickets_solicitantes_select ON public.tickets_solicitantes;
    DROP POLICY IF EXISTS tickets_solicitantes_insert ON public.tickets_solicitantes;
    DROP POLICY IF EXISTS tickets_solicitantes_delete ON public.tickets_solicitantes;
    CREATE POLICY tickets_solicitantes_select ON public.tickets_solicitantes
        FOR SELECT TO authenticated USING (true);
    CREATE POLICY tickets_solicitantes_insert ON public.tickets_solicitantes
        FOR INSERT TO authenticated WITH CHECK (true);
    CREATE POLICY tickets_solicitantes_delete ON public.tickets_solicitantes
        FOR DELETE TO authenticated USING (true);
END;
$$;

-- Migrar los solicitantes actuales (uno solo) a la tabla de unión.
INSERT INTO public.tickets_solicitantes (id_ticket, id_entidad_relacionada)
SELECT t.id, t.id_entidad_relacionada
FROM public.tickets t
WHERE t.id_entidad_relacionada IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM public.tickets_solicitantes ts
    WHERE ts.id_ticket = t.id AND ts.id_entidad_relacionada = t.id_entidad_relacionada
  );
