-- =============================================================================
-- tipos_documento — id 63: INE completo (frente y reverso en un solo PDF)
--
-- El portal cliente dejó de capturar la identificación con cámara y validación
-- biométrica: ahora el cliente sube un único PDF escaneado con las dos vistas y
-- la validación es manual. El par histórico Frente INE (2) + Reverso INE (3) ya
-- no aplica a ese archivo, así que se da de alta un tipo propio en lugar de
-- ensuciar el significado de 2 y 3.
--
-- El id es fijo porque el frontend lo referencia como INE_COMPLETO_TIPO_ID = 63
-- (src/pages/admin/portal-cliente/ClientePerfil.tsx y el grupo 'ine' de los
-- expedientes). Hasta que exista la fila, el portal bloquea la subida: el INSERT
-- en documentos fallaría por FK.
--
-- Verificado read-only contra prod el 2026-07-29:
--   · tipos_documento: 57 filas, MAX(id) = 62, id 63 libre.
--   · id es integer GENERATED BY DEFAULT AS IDENTITY → valor explícito permitido
--     sin OVERRIDING SYSTEM VALUE.
--   · categorias_tipo_documento.id = 1 → 'Identificación' (igual que 2, 3 y 4).
--   · padre y asignado_a son text sin CHECK: 'pf' / 'per' no requieren catálogo.
--   · Ninguna función de la base filtra por id_tipo_documento IN (2,3) ni
--     = 2 / = 3, y ninguna vista referencia id_tipo_documento: el agrupado del
--     grupo 'ine' es solo de frontend, no hay gate de escrituración que tocar.
--   · La tabla no tenía COMMENT previo: el de esta migración no pisa nada.
--
-- Correcciones respecto al documento de la solicitud:
--   a) La tabla tiene UNIQUE (nombre) además de la PK. Con ON CONFLICT (id) DO
--      NOTHING, un nombre ya usado con otro id (drift de dev) reventaría con
--      23505 y rompería el CI. Aquí el alta va guarded contra ambas llaves y la
--      migración ABORTA con mensaje explícito si el nombre existe con otro id:
--      eso es drift real y no conviene saltárselo en silencio.
--   b) El setval no es solo higiene por fijar el id a mano: la secuencia YA
--      estaba atrasada en prod (last_value = 57 contra MAX(id) = 62), así que
--      hoy un INSERT sin id explícito colisiona con los ids 58-62. Esta
--      migración también arregla eso.
--
-- Sin backfill y sin DDL: los documentos históricos de tipos 2/3 se quedan como
-- están y la FK documentos.id_tipo_documento ya apunta a tipos_documento(id).
-- =============================================================================

-- Guard de drift: el nombre es UNIQUE. Si ya existe con otro id, el frontend
-- (que tiene 63 hardcodeado) quedaría apuntando al tipo equivocado.
DO $$
DECLARE
  v_id_existente integer;
BEGIN
  SELECT id INTO v_id_existente
  FROM public.tipos_documento
  WHERE nombre = 'INE completo (frente y reverso)';

  IF v_id_existente IS NOT NULL AND v_id_existente <> 63 THEN
    RAISE EXCEPTION
      'El tipo "INE completo (frente y reverso)" ya existe con id % (se esperaba 63). '
      'El frontend usa INE_COMPLETO_TIPO_ID = 63: resolver el drift antes de aplicar.',
      v_id_existente;
  END IF;

  IF EXISTS (SELECT 1 FROM public.tipos_documento WHERE id = 63) THEN
    RAISE NOTICE 'tipos_documento.id = 63 ya existe, no se inserta';
  ELSE
    INSERT INTO public.tipos_documento
      (id, nombre, activo, padre, id_categoria_documento, asignado_a)
    VALUES
      (63, 'INE completo (frente y reverso)', true, 'pf', 1, 'per');
  END IF;
END
$$;

COMMENT ON TABLE public.tipos_documento IS
  'Catálogo de tipos de documento. id 63 = INE completo (frente y reverso en un '
  'solo PDF escaneado), formato que sube el portal cliente desde 2026-07-29; los '
  'ids 2 y 3 (frente/reverso por separado) quedan solo para cargas históricas.';

-- La secuencia de identidad tiene que quedar por encima del máximo real. En prod
-- estaba en 57 con MAX(id) = 62, así que esto arregla también las colisiones que
-- ya existían para cualquier INSERT sin id explícito.
SELECT setval(
  pg_get_serial_sequence('public.tipos_documento', 'id'),
  (SELECT MAX(id) FROM public.tipos_documento)
);

-- -----------------------------------------------------------------------------
-- Self-verifying: aborta el CI si el catálogo o la secuencia no quedaron bien.
-- -----------------------------------------------------------------------------
DO $$
DECLARE
  v_r     record;
  v_seq   text := pg_get_serial_sequence('public.tipos_documento', 'id');
  v_last  bigint;
  v_max   integer;
BEGIN
  SELECT id, nombre, activo, padre, id_categoria_documento, asignado_a
    INTO v_r
  FROM public.tipos_documento WHERE id = 63;

  IF v_r.id IS NULL THEN
    RAISE EXCEPTION 'No se creó tipos_documento.id = 63';
  END IF;

  IF v_r.nombre <> 'INE completo (frente y reverso)'
     OR v_r.activo IS NOT TRUE
     OR v_r.padre IS DISTINCT FROM 'pf'
     OR v_r.id_categoria_documento <> 1
     OR v_r.asignado_a IS DISTINCT FROM 'per' THEN
    RAISE EXCEPTION 'La fila 63 no quedó con los valores esperados: %', v_r;
  END IF;

  -- Misma categoría que el resto de las identificaciones (2 Frente INE,
  -- 3 Reverso INE, 4 Pasaporte).
  IF (SELECT count(*) FROM public.tipos_documento
      WHERE id IN (2, 3, 4, 63) AND id_categoria_documento = 1) <> 4 THEN
    RAISE EXCEPTION 'Los tipos 2/3/4/63 deberían estar todos en la categoría 1 (Identificación)';
  END IF;

  -- Un solo id para ese nombre (UNIQUE lo garantiza, pero deja el fallo claro).
  IF (SELECT count(*) FROM public.tipos_documento
      WHERE nombre = 'INE completo (frente y reverso)') <> 1 THEN
    RAISE EXCEPTION 'Hay más de una fila con el nombre del INE completo';
  END IF;

  -- La secuencia no puede quedar por debajo del máximo o el siguiente INSERT
  -- sin id explícito daría 23505.
  SELECT last_value INTO v_last FROM pg_sequences
  WHERE schemaname = 'public' AND sequencename = split_part(v_seq, '.', 2);
  SELECT MAX(id) INTO v_max FROM public.tipos_documento;

  IF v_last IS NULL OR v_last < v_max THEN
    RAISE EXCEPTION 'La secuencia % quedó en % con MAX(id) = %', v_seq, v_last, v_max;
  END IF;
END
$$;
