-- Catálogo gestionable: etapa del ciclo de vida del CRM → evento de Meta (Conversions
-- API for Leads). Reemplaza el CAPI_STAGE_MAP hardcodeado de crm.tsx. La pantalla
-- /marketing/meta → "Eventos de conversión" hace CRUD contra esta tabla.
--   etapa_ciclo_vida = valor de crm_leads_atribucion.etapa_ciclo_vida (lead/mql/sql/...)
--   meta_event_name  = event_name que espera Meta (debe coincidir con Events Manager)
--   activo           = si esa etapa dispara señal a Meta (seed: solo MQL activo)
-- Self-guarded + idempotente.

CREATE TABLE IF NOT EXISTS public.crm_meta_conversion_stages (
    id                  INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    etapa_ciclo_vida    TEXT         NOT NULL UNIQUE,
    meta_event_name     TEXT         NOT NULL,
    activo              BOOLEAN      NOT NULL DEFAULT TRUE,
    orden               INTEGER      NOT NULL DEFAULT 100,
    fecha_creacion      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    fecha_actualizacion TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Seed: etapas del ciclo de vida → evento de Meta. Solo MQL activo por defecto.
INSERT INTO public.crm_meta_conversion_stages (etapa_ciclo_vida, meta_event_name, activo, orden) VALUES
  ('lead',        'lead',        false, 10),
  ('mql',         'mql',         true,  20),
  ('sql',         'sql',         false, 30),
  ('opportunity', 'opportunity', false, 40),
  ('customer',    'purchase',    false, 50)
ON CONFLICT (etapa_ciclo_vida) DO NOTHING;

-- RLS: lectura + escritura para usuarios autenticados (config del CRM, pantalla admin-gated).
ALTER TABLE public.crm_meta_conversion_stages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "crm_meta_conv_all" ON public.crm_meta_conversion_stages;
CREATE POLICY "crm_meta_conv_all"
  ON public.crm_meta_conversion_stages
  FOR ALL TO authenticated
  USING (true) WITH CHECK (true);
