-- =============================================================================
-- Oferta digital — guardar_csf_oferta(...)
--
-- Al confirmar sus datos el cliente puede subir su Constancia de Situación
-- Fiscal. El archivo va al bucket 'documentos' (política existente 'Anyone can
-- upload documents'), pero registrar la fila en documentos y escribir los datos
-- fiscales en personas no es posible desde anon (personas_update es solo para
-- authenticated). De ahí esta función, identificada por el token de la
-- reservación como el resto del flujo público.
--
-- Verificado read-only contra prod el 2026-07-28:
--   · guardar_csf_oferta no existe con ninguna firma.
--   · tipos_documento.id = 6 → 'Constancia de situación fiscal'.
--     estatus_verificacion.id = 2 → 'Validado'.
--   · documentos.id es identity (GENERATED BY DEFAULT): el INSERT sin id va bien.
--     activo default true, fecha_creacion/actualizacion default CURRENT_TIMESTAMP,
--     es_draft default false. No hay columna 'nombre'.
--   · 971 documentos tipo 6 (921 activos), 971/971 con url de /storage/v1/object/.
--   · Todas las columnas de personas del spec existen.
--
-- Correcciones respecto al spec, contra el esquema real:
--   a) documentos tiene UNIQUE (url) y CHECK (url ~* '^(https?|/).+'). El INSERT
--      del spec lanza 23505 en cualquier reintento/doble clic (storage hace
--      upsert sobre el mismo path → misma url pública) y 23514 si el front manda
--      un path sin esquema. Ambos llegan al cliente como 500 sin guardar nada.
--      Aquí: se valida el formato antes, y si la url ya está registrada para la
--      MISMA persona se reactiva esa fila en lugar de insertar.
--   b) Seguridad: si la url ya pertenece a OTRA persona se devuelve false sin
--      tocar nada. Resolver el UNIQUE con un ON CONFLICT ciego permitiría a anon
--      mandar la url del documento de otro y reasignárselo, desactivando el del
--      dueño. Además la url debe ser del bucket 'documentos' (el único donde anon
--      puede subir): así no se registran urls arbitrarias como documento.
--   c) chk_personas_cp_dir_fiscal exige btrim(cp) ~ '^[0-9]{4,10}$'. Un CP con
--      letras o de 3 dígitos daba 23514 → 500. Se descarta en silencio.
--   d) direccion_fiscal_calle es character(100) y direccion_fiscal_codigo_postal
--      character(10), no text: un valor más largo daba 22001 → 500. Se truncan.
--      El btrim en las comparaciones es obligatorio por el padding de char(n).
--   e) regimen conserva su valor previo si los dos lados vienen vacíos (el spec
--      escribía NULL por falta del último fallback).
--   f) El INSERT va dentro de un bloque con EXCEPTION: el trigger
--      on_document_insert_or_update_sat (tipos 6, 21, 22) llama a
--      check_sat_notification_conditions(), que usa extensions.http_post y la
--      extensión http NO está instalada en prod (solo pg_net). Si se cumplen sus
--      condiciones (propiedad en estatus 9 + factura validada + CSF validada)
--      lanza 42883 y aborta el INSERT. Hoy 0 leads activos entran en ese camino,
--      pero el handler evita el 500 y deja WARNING en el log.
--      PENDIENTE APARTE: esa ruta está rota para todos los flujos, no solo este,
--      y dispara una notificación SAT real. Se arregla en su propia migración.
--
-- Nota de seguridad (NO se toca aquí, pero conviene saberlo): el bucket
-- 'documentos' es público y sus políticas de storage.objects para el rol public
-- son 'Anyone can upload/update/delete documents' sin condición de propiedad.
-- Es decir, con la anon key hoy se puede sobrescribir o borrar CUALQUIER objeto
-- del bucket, no solo el propio, y leer cualquiera con su url. Endurecerlo es
-- una migración aparte.
-- =============================================================================

CREATE OR REPLACE FUNCTION public.guardar_csf_oferta(
  p_token       uuid    DEFAULT NULL,
  p_url         text    DEFAULT NULL,
  p_rfc         text    DEFAULT NULL,
  p_curp        text    DEFAULT NULL,
  p_nombre      text    DEFAULT NULL,
  p_regimen     text    DEFAULT NULL,
  p_cp          text    DEFAULT NULL,
  p_calle       text    DEFAULT NULL,
  p_num_ext     text    DEFAULT NULL,
  p_num_int     text    DEFAULT NULL,
  p_colonia     text    DEFAULT NULL
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_id_oferta   integer;
  v_id_persona  integer;
  v_url         text;
  v_doc_id      bigint;
  v_doc_persona integer;
  v_rfc         text;
  v_curp        text;
  v_cp          text;
BEGIN
  -- Fallo cerrado: sin token o sin archivo no se escribe nada.
  v_url := NULLIF(btrim(COALESCE(p_url, '')), '');
  IF p_token IS NULL OR v_url IS NULL THEN
    RETURN false;
  END IF;

  -- La url tiene que cumplir chk_doc_url_formato y ser del bucket donde anon
  -- puede subir. Sin esto: 23514 (500 al cliente) o registro de urls ajenas.
  IF v_url !~* '^(https?|/).+'
     OR position('/storage/v1/object/public/documentos/' in v_url) = 0 THEN
    RETURN false;
  END IF;

  SELECT r.id_oferta INTO v_id_oferta
  FROM reservaciones r
  WHERE r.token = p_token
    AND r.activo = true
    AND r.estatus NOT IN ('expirado', 'cancelado')
    AND (r.fecha_expiracion IS NULL OR r.fecha_expiracion > now());

  IF v_id_oferta IS NULL THEN
    RETURN false;
  END IF;

  SELECT o.id_persona_lead INTO v_id_persona
  FROM ofertas o WHERE o.id = v_id_oferta AND o.activo = true;

  IF v_id_persona IS NULL THEN
    RETURN false;
  END IF;

  -- UNIQUE (url): si ya está registrada, solo se reutiliza cuando es de esta
  -- misma persona. De otro modo se podría reasignar el documento de otro.
  SELECT d.id, d.id_persona INTO v_doc_id, v_doc_persona
  FROM documentos d WHERE d.url = v_url;

  IF v_doc_id IS NOT NULL AND v_doc_persona IS DISTINCT FROM v_id_persona THEN
    RETURN false;
  END IF;

  -- RFC/CURP: se descartan en silencio si no cumplen formato o ya pertenecen a
  -- otra persona (misma regla que update_lead_datos, para no lanzar 500 a anon
  -- ni usar la violación de UNIQUE como oráculo de existencia).
  v_rfc := NULLIF(upper(btrim(COALESCE(p_rfc, ''))), '');
  IF v_rfc IS NOT NULL
     AND (v_rfc !~ '^[A-Z&Ñ]{3,4}[0-9]{6}[A-Z0-9]{3}$'
          OR EXISTS (SELECT 1 FROM personas x WHERE x.rfc = v_rfc AND x.id <> v_id_persona))
  THEN
    v_rfc := NULL;
  END IF;

  v_curp := NULLIF(upper(btrim(COALESCE(p_curp, ''))), '');
  IF v_curp IS NOT NULL
     AND (v_curp !~ '^[A-Z]{4}[0-9]{6}[HM][A-Z]{5}[A-Z0-9]{2}$'
          OR EXISTS (SELECT 1 FROM personas x WHERE x.curp = v_curp AND x.id <> v_id_persona))
  THEN
    v_curp := NULL;
  END IF;

  -- CP: chk_personas_cp_dir_fiscal exige 4-10 dígitos.
  v_cp := NULLIF(btrim(COALESCE(p_cp, '')), '');
  IF v_cp IS NOT NULL AND v_cp !~ '^[0-9]{4,10}$' THEN
    v_cp := NULL;
  END IF;

  -- Ver nota (f): el trigger de SAT puede lanzar excepción. Se atrapa para
  -- devolver false en lugar de un 500, y sin haber tocado personas todavía.
  -- La desactivación de la CSF anterior va DENTRO del bloque: si el INSERT
  -- falla, el rollback del subbloque la deshace y la persona no se queda sin
  -- ninguna CSF activa.
  BEGIN
    -- Una sola CSF activa por persona (sin apagar la fila que se reutiliza).
    UPDATE documentos
       SET activo = false, fecha_actualizacion = now()
     WHERE id_persona = v_id_persona
       AND id_tipo_documento = 6
       AND activo = true
       AND url <> v_url;

    IF v_doc_id IS NULL THEN
      INSERT INTO documentos (url, id_tipo_documento, id_persona, activo, id_estatus_verificacion)
      VALUES (v_url, 6, v_id_persona, true, 2);
    ELSE
      UPDATE documentos
         SET id_tipo_documento = 6,
             activo = true,
             id_estatus_verificacion = 2,
             fecha_actualizacion = now()
       WHERE id = v_doc_id;
    END IF;
  EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'guardar_csf_oferta: documento no registrado (% - %)', SQLSTATE, SQLERRM;
    RETURN false;
  END;

  -- Datos fiscales: solo se rellenan las columnas vacías, nunca se pisa un dato
  -- capturado o validado por el equipo. btrim por el padding de char(n).
  BEGIN
    UPDATE personas SET
      rfc  = CASE WHEN v_rfc  IS NOT NULL AND NULLIF(btrim(COALESCE(rfc,  '')), '') IS NULL
                  THEN v_rfc  ELSE rfc  END,
      curp = CASE WHEN v_curp IS NOT NULL AND NULLIF(btrim(COALESCE(curp, '')), '') IS NULL
                  THEN v_curp ELSE curp END,
      nombre_legal = COALESCE(
        NULLIF(btrim(COALESCE(nombre_legal, '')), ''),
        NULLIF(btrim(COALESCE(p_nombre, '')), ''),
        nombre_legal),
      regimen = COALESCE(
        NULLIF(btrim(COALESCE(regimen, '')), ''),
        NULLIF(btrim(COALESCE(p_regimen, '')), ''),
        regimen),
      -- character(10): el regex ya limita a 10 dígitos.
      direccion_fiscal_codigo_postal = COALESCE(
        NULLIF(btrim(COALESCE(direccion_fiscal_codigo_postal, '')), ''),
        v_cp,
        direccion_fiscal_codigo_postal),
      -- character(100): truncar o sería 22001.
      direccion_fiscal_calle = COALESCE(
        NULLIF(btrim(COALESCE(direccion_fiscal_calle, '')), ''),
        left(NULLIF(btrim(COALESCE(p_calle, '')), ''), 100),
        direccion_fiscal_calle),
      direccion_fiscal_num_ext = COALESCE(
        NULLIF(btrim(COALESCE(direccion_fiscal_num_ext, '')), ''),
        NULLIF(btrim(COALESCE(p_num_ext, '')), ''),
        direccion_fiscal_num_ext),
      direccion_fiscal_num_int = COALESCE(
        NULLIF(btrim(COALESCE(direccion_fiscal_num_int, '')), ''),
        NULLIF(btrim(COALESCE(p_num_int, '')), ''),
        direccion_fiscal_num_int),
      direccion_fiscal_colonia = COALESCE(
        NULLIF(btrim(COALESCE(direccion_fiscal_colonia, '')), ''),
        NULLIF(btrim(COALESCE(p_colonia, '')), ''),
        direccion_fiscal_colonia),
      fecha_actualizacion = now()
    WHERE id = v_id_persona;
  EXCEPTION WHEN OTHERS THEN
    -- El documento ya quedó registrado: se reporta true y se deja el WARNING.
    -- Los datos fiscales los puede completar el equipo desde el panel.
    RAISE WARNING 'guardar_csf_oferta: datos fiscales no escritos (% - %)', SQLSTATE, SQLERRM;
  END;

  RETURN true;
END;
$$;

REVOKE ALL ON FUNCTION public.guardar_csf_oferta(uuid, text, text, text, text, text, text, text, text, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.guardar_csf_oferta(uuid, text, text, text, text, text, text, text, text, text, text)
  TO anon, authenticated, service_role;

COMMENT ON FUNCTION public.guardar_csf_oferta(uuid, text, text, text, text, text, text, text, text, text, text) IS
  'Oferta digital pública: registra la Constancia de Situación Fiscal que subió el '
  'cliente (documentos tipo 6, validada, url del bucket documentos) y rellena los '
  'datos fiscales vacíos de la persona del lead. Se identifica por el token de la '
  'reservación; sin token válido, sin url válida, o si la url ya es de otra persona, '
  'devuelve false sin escribir nada.';

-- -----------------------------------------------------------------------------
-- Guard de sobrecargas. CREATE OR REPLACE no reemplaza una firma distinta: la
-- agrega y PostgREST deja de resolver la llamada. En prod no existe ninguna
-- versión previa (verificado 2026-07-28); los DROP van guarded por si hay drift
-- en dev.
-- -----------------------------------------------------------------------------
DO $$
DECLARE
  v_sig text;
BEGIN
  FOREACH v_sig IN ARRAY ARRAY[
    'public.guardar_csf_oferta(uuid, text)',
    'public.guardar_csf_oferta(uuid, text, text)',
    'public.guardar_csf_oferta(uuid, text, text, text)',
    'public.guardar_csf_oferta(uuid, text, text, text, text)',
    'public.guardar_csf_oferta(uuid, text, text, text, text, text)',
    'public.guardar_csf_oferta(uuid, text, text, text, text, text, text)',
    'public.guardar_csf_oferta(uuid, text, text, text, text, text, text, text)',
    'public.guardar_csf_oferta(uuid, text, text, text, text, text, text, text, text)',
    'public.guardar_csf_oferta(uuid, text, text, text, text, text, text, text, text, text)',
    'public.guardar_csf_oferta(integer, text)'
  ]
  LOOP
    IF to_regprocedure(v_sig) IS NOT NULL THEN
      EXECUTE format('DROP FUNCTION %s', v_sig);
      RAISE NOTICE 'Eliminada sobrecarga previa %', v_sig;
    END IF;
  END LOOP;
END
$$;

-- -----------------------------------------------------------------------------
-- Self-verifying: aborta el CI si algo no quedó como se espera.
-- Solo smoke tests que NO escriben (token NULL, url NULL, url de otro bucket).
-- -----------------------------------------------------------------------------
DO $$
DECLARE
  v_n integer;
BEGIN
  SELECT count(*) INTO v_n
  FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
  WHERE n.nspname = 'public' AND p.proname = 'guardar_csf_oferta';
  IF v_n <> 1 THEN
    RAISE EXCEPTION 'Se esperaba 1 firma de guardar_csf_oferta, hay %', v_n;
  END IF;

  IF to_regprocedure('public.guardar_csf_oferta(uuid, text, text, text, text, text, text, text, text, text, text)') IS NULL THEN
    RAISE EXCEPTION 'Falta la firma nueva de guardar_csf_oferta';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public' AND p.proname = 'guardar_csf_oferta' AND p.prosecdef = true
  ) THEN
    RAISE EXCEPTION 'guardar_csf_oferta quedó sin SECURITY DEFINER';
  END IF;

  IF NOT has_function_privilege('anon', 'public.guardar_csf_oferta(uuid, text, text, text, text, text, text, text, text, text, text)', 'EXECUTE')
     OR NOT has_function_privilege('authenticated', 'public.guardar_csf_oferta(uuid, text, text, text, text, text, text, text, text, text, text)', 'EXECUTE') THEN
    RAISE EXCEPTION 'anon/authenticated no pueden ejecutar guardar_csf_oferta';
  END IF;

  -- Los catálogos que la función da por hechos.
  IF NOT EXISTS (SELECT 1 FROM tipos_documento WHERE id = 6) THEN
    RAISE EXCEPTION 'tipos_documento.id = 6 (CSF) no existe';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM estatus_verificacion WHERE id = 2) THEN
    RAISE EXCEPTION 'estatus_verificacion.id = 2 (Validado) no existe';
  END IF;

  -- Rechazos sin escritura.
  IF public.guardar_csf_oferta(NULL, 'https://x.supabase.co/storage/v1/object/public/documentos/a.pdf') THEN
    RAISE EXCEPTION 'Token NULL no devolvió false';
  END IF;

  IF public.guardar_csf_oferta('00000000-0000-0000-0000-000000000000', NULL) THEN
    RAISE EXCEPTION 'url NULL no devolvió false';
  END IF;

  IF public.guardar_csf_oferta('00000000-0000-0000-0000-000000000000',
       'https://x.supabase.co/storage/v1/object/public/otro-bucket/a.pdf') THEN
    RAISE EXCEPTION 'url fuera del bucket documentos no devolvió false';
  END IF;

  IF EXISTS (
    SELECT 1 FROM documentos
    WHERE url IN ('https://x.supabase.co/storage/v1/object/public/documentos/a.pdf',
                  'https://x.supabase.co/storage/v1/object/public/otro-bucket/a.pdf')
  ) THEN
    RAISE EXCEPTION 'Los smoke tests escribieron en documentos';
  END IF;
END
$$;
