-- Motivo de no avance de Ofertas — Pipeline del Portal de Agentes (/admin/agent/pipeline)
-- Fecha: 2026-08-04
--
-- Toda oferta clasificada como «Expirada» debe pedir al agente la razón por la que no avanzó
-- de etapa (hoy se pierde la causa comercial). La etapa `expiradas` es DERIVADA en el front
-- (classifyOffer), no persistida → el registro se ancla a id_oferta, no a un estatus.
--
-- Construye:
--   1. Catálogo `motivos_no_avance_oferta` (razones estandarizadas, claves estables).
--   2. Registro `ofertas_no_avance` (una razón vigente por oferta vía índice único parcial).
--   3. Vista `v_ofertas_no_avance` (motivo resuelto por oferta, security_invoker, para tableros).
--
-- Convención de esquema: ambas tablas tienen activo, fecha_creacion y fecha_actualizacion, y un
-- trigger BEFORE UPDATE que refresca fecha_actualizacion vía la función existente del esquema base
-- public.set_fecha_actualizacion() (NEW.fecha_actualizacion = now()).
--
-- El front usa DDL probe: mientras las tablas no existan muestra «pendiente de habilitar».
-- La captura se rige por el permiso `actualizar` (id 3) del submenú existente /admin/agent/pipeline;
-- NO se crea menú/submenú nuevo.
--
-- Idempotente: CREATE TABLE/INDEX IF NOT EXISTS, CREATE OR REPLACE VIEW,
-- DROP TRIGGER/POLICY IF EXISTS + CREATE, ON CONFLICT (clave) DO UPDATE. Sin BEGIN/COMMIT
-- (CI/CD envuelve en tx). El NOTIFY final se entrega al commit de esa tx.

-- ── 1. Catálogo de motivos ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.motivos_no_avance_oferta (
  id                  smallint     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clave               text         NOT NULL UNIQUE,
  nombre              text         NOT NULL,
  descripcion         text,
  requiere_comentario boolean      NOT NULL DEFAULT false,
  es_recuperable      boolean      NOT NULL DEFAULT true,
  orden               smallint     NOT NULL DEFAULT 100,
  activo              boolean      NOT NULL DEFAULT true,
  fecha_creacion      timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_actualizacion timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE  public.motivos_no_avance_oferta IS
  'Catálogo de razones por las que una oferta no avanzó a la siguiente etapa del pipeline.';
COMMENT ON COLUMN public.motivos_no_avance_oferta.clave IS
  'Slug estable consumido por el front; no cambiar una vez publicado.';
COMMENT ON COLUMN public.motivos_no_avance_oferta.requiere_comentario IS
  'Si es true, el front obliga a capturar comentario antes de guardar.';
COMMENT ON COLUMN public.motivos_no_avance_oferta.es_recuperable IS
  'true = el prospecto puede retomarse (timing, presupuesto); false = caída definitiva.';

CREATE INDEX IF NOT EXISTS idx_motivos_no_avance_oferta_activo
  ON public.motivos_no_avance_oferta (activo, orden);

DROP TRIGGER IF EXISTS trg_motivos_no_avance_oferta_touch ON public.motivos_no_avance_oferta;
CREATE TRIGGER trg_motivos_no_avance_oferta_touch
  BEFORE UPDATE ON public.motivos_no_avance_oferta
  FOR EACH ROW EXECUTE FUNCTION public.set_fecha_actualizacion();

-- ── 2. Registro por oferta ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.ofertas_no_avance (
  id                  bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_oferta           integer      NOT NULL
                        REFERENCES public.ofertas (id) ON DELETE CASCADE,
  id_motivo           smallint     NOT NULL
                        REFERENCES public.motivos_no_avance_oferta (id),
  comentario          text,
  registrado_por      text,
  activo              boolean      NOT NULL DEFAULT true,
  fecha_creacion      timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_actualizacion timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE  public.ofertas_no_avance IS
  'Razón capturada por el agente de por qué una oferta expirada no avanzó de etapa.';
COMMENT ON COLUMN public.ofertas_no_avance.registrado_por IS
  'Email del usuario que capturó la razón (no FK: puede capturarla un admin dado de baja después).';

-- Una sola razón vigente por oferta (permite corregirla con UPDATE).
CREATE UNIQUE INDEX IF NOT EXISTS uq_ofertas_no_avance_oferta_activa
  ON public.ofertas_no_avance (id_oferta) WHERE activo;

CREATE INDEX IF NOT EXISTS idx_ofertas_no_avance_motivo
  ON public.ofertas_no_avance (id_motivo) WHERE activo;

-- Mantener fecha_actualizacion (función existente del esquema base).
DROP TRIGGER IF EXISTS trg_ofertas_no_avance_touch ON public.ofertas_no_avance;
CREATE TRIGGER trg_ofertas_no_avance_touch
  BEFORE UPDATE ON public.ofertas_no_avance
  FOR EACH ROW EXECUTE FUNCTION public.set_fecha_actualizacion();

-- ── 3. Seed del catálogo ────────────────────────────────────────────────────
INSERT INTO public.motivos_no_avance_oferta
  (clave, nombre, descripcion, requiere_comentario, es_recuperable, orden)
VALUES
  ('fuera_presupuesto',   'Está fuera de presupuesto',
   'El precio total supera lo que el prospecto puede o quiere pagar.',            false, true,  10),
  ('no_listo_compra',     'No está listo para la compra',
   'Interesado, pero pospone la decisión (timing, trámites, venta previa).',      false, true,  20),
  ('no_es_el_producto',   'No es el producto que busca',
   'Metros, recámaras, piso, vista o amenidades no corresponden a lo que quiere.', false, true,  30),
  ('financiamiento',      'No le agradó el financiamiento',
   'Enganche, plazo, mensualidad o tasa del esquema de pago no le funcionaron.',  false, true,  40),
  ('contrato',            'No le gustó el contrato',
   'Cláusulas, penalizaciones o condiciones legales frenaron el cierre.',         false, true,  50),
  ('ubicacion',           'No le convenció la ubicación',
   'Zona, entorno o distancia del proyecto.',                                     false, true,  60),
  ('fecha_entrega',       'La fecha de entrega no le funciona',
   'Necesita ocuparla antes de lo que el proyecto puede entregar.',               false, true,  70),
  ('credito_rechazado',   'No calificó al crédito',
   'Rechazo o insuficiencia de crédito hipotecario / buró.',                      false, true,  80),
  ('eligio_competencia',  'Eligió otra opción / competencia',
   'Compró o apartó con otro desarrollo o desarrollador.',                        false, false, 90),
  ('sin_respuesta',       'Dejó de responder',
   'Se perdió contacto con el prospecto tras enviar la oferta.',                  false, true,  100),
  ('unidad_no_disponible','La unidad ya no estaba disponible',
   'Se apartó o vendió a otro prospecto antes del cierre.',                       false, true,  110),
  ('oferta_duplicada',    'Oferta duplicada o generada por error',
   'Se emitió por error, con datos incorrectos o se sustituyó por otra oferta.',  false, false, 120),
  ('otro',                'Otro motivo',
   'Cualquier razón no contemplada; requiere detalle escrito.',                   true,  true,  999)
ON CONFLICT (clave) DO UPDATE
  SET nombre              = EXCLUDED.nombre,
      descripcion         = EXCLUDED.descripcion,
      requiere_comentario = EXCLUDED.requiere_comentario,
      es_recuperable      = EXCLUDED.es_recuperable,
      orden               = EXCLUDED.orden,
      activo              = true;

SELECT setval(
  pg_get_serial_sequence('public.motivos_no_avance_oferta', 'id'),
  (SELECT MAX(id) FROM public.motivos_no_avance_oferta)
);

-- ── 4. Vista de reporte ─────────────────────────────────────────────────────
CREATE OR REPLACE VIEW public.v_ofertas_no_avance
WITH (security_invoker = true) AS
SELECT
  na.id_oferta,
  o.email_creador,
  o.fecha_generacion,
  o.id_propiedad,
  o.id_producto,
  o.id_persona_lead,
  m.clave           AS motivo_clave,
  m.nombre          AS motivo_nombre,
  m.es_recuperable,
  na.comentario,
  na.registrado_por,
  na.fecha_creacion
FROM public.ofertas_no_avance na
JOIN public.motivos_no_avance_oferta m ON m.id = na.id_motivo
JOIN public.ofertas o                  ON o.id = na.id_oferta
WHERE na.activo;

COMMENT ON VIEW public.v_ofertas_no_avance IS
  'Motivo vigente de no avance por oferta, resuelto contra el catálogo. Para tableros.';

-- ── 5. RLS y permisos ───────────────────────────────────────────────────────
ALTER TABLE public.motivos_no_avance_oferta ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ofertas_no_avance        ENABLE ROW LEVEL SECURITY;

-- Catálogo: lectura pública autenticada/anónima (igual que el resto de catálogos).
DROP POLICY IF EXISTS motivos_no_avance_oferta_select ON public.motivos_no_avance_oferta;
CREATE POLICY motivos_no_avance_oferta_select
  ON public.motivos_no_avance_oferta
  FOR SELECT TO anon, authenticated
  USING (true);

-- Registro: lectura para cualquier usuario autenticado (admin y dirección auditan).
DROP POLICY IF EXISTS ofertas_no_avance_select ON public.ofertas_no_avance;
CREATE POLICY ofertas_no_avance_select
  ON public.ofertas_no_avance
  FOR SELECT TO authenticated
  USING (true);

DROP POLICY IF EXISTS ofertas_no_avance_insert ON public.ofertas_no_avance;
CREATE POLICY ofertas_no_avance_insert
  ON public.ofertas_no_avance
  FOR INSERT TO authenticated
  WITH CHECK ((SELECT auth.uid()) IS NOT NULL);

DROP POLICY IF EXISTS ofertas_no_avance_update ON public.ofertas_no_avance;
CREATE POLICY ofertas_no_avance_update
  ON public.ofertas_no_avance
  FOR UPDATE TO authenticated
  USING ((SELECT auth.uid()) IS NOT NULL)
  WITH CHECK ((SELECT auth.uid()) IS NOT NULL);

-- Sin política de DELETE: la corrección se hace por UPDATE.

-- Las columnas son IDENTITY, no `serial`: no se requiere GRANT sobre la secuencia.
GRANT SELECT                   ON public.motivos_no_avance_oferta TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE   ON public.ofertas_no_avance        TO authenticated;
GRANT SELECT                   ON public.v_ofertas_no_avance      TO authenticated;

-- Refrescar el cache de esquema de PostgREST para que el front vea las tablas
-- nuevas y la relación embebida `ofertas_no_avance → motivos_no_avance_oferta`.
NOTIFY pgrst, 'reload schema';
