-- Tipos de documento para cancelaciones y devoluciones de cuentas de cobranza
-- Fecha: 2026-08-12
-- Origen: Ejecuciones/ejecusiones.md
--
-- ─── Qué cambia ───────────────────────────────────────────────────────────────
-- Alta en el catalogo public.tipos_documento de los tres tipos que hoy no existen y que
-- se necesitan para documentar una cuenta de cobranza cancelada (de propiedad o de
-- producto):
--
--   Nota de credito                          nota de credito emitida al cliente
--   Evidencia de devolucion                  evidencia de que se devolvio el dinero
--   Comprobante de transferencia al cliente  comprobante bancario de la transferencia
--
-- Con estos, el modal "Agregar documentos" del detalle de la cuenta
-- (/admin/cuentas-cobranza/:id/detalle) ofrece las cinco opciones pedidas: los tres
-- nuevos mas Factura XML y Factura PDF, que ya existen.
--
-- ─── Estado verificado read-only contra produccion el 2026-08-12 ──────────────
-- · Ninguno de los tres nombres existe todavia. Lo mas cercano es "Comprobante de pago"
--   (id 31, padre='p', asignado_a='prop', categoria 8), que se usa para pagos del cliente
--   HACIA SOZU, no para devoluciones — por eso no se reutiliza.
-- · Factura XML (21) y Factura PDF (22) ya existen: padre='a', asignado_a='prop',
--   categoria 7. No se tocan.
-- · Las categorias 4 (Comprobante fiscal) y 8 (Comprobante de pago) existen.
-- · `padre` admite hoy a / p / pf / pm y `asignado_a` admite comision / per / prop, asi
--   que los valores usados son validos. No hay CHECK que los restrinja: son texto libre.
-- · `tipos_documento.id` es GENERATED BY DEFAULT AS IDENTITY, asi que omitirlo es correcto.
--
-- ─── Decisiones ───────────────────────────────────────────────────────────────
-- · Categorias: 4 (Comprobante fiscal) para la nota de credito, porque es un CFDI; y 8
--   (Comprobante de pago) para la evidencia de devolucion y el comprobante de
--   transferencia, porque ambos son evidencia de movimiento de dinero.
-- · OJO con la categoria 7: el detalle de la cuenta la usa para calcular "Documentos de
--   entrega faltantes". Los tipos nuevos NO van en la 7 para no ensuciar ese calculo.
-- · padre='p' y asignado_a='prop' para los tres: cuelgan de la cuenta/propiedad, no de la
--   persona. Mismo criterio que los tipos 31 "Comprobante de pago" y 39 "Convenio de
--   terminacion de contrato", verificados en produccion.
-- · NO se fija `id` manualmente. El front (SubirDocumentosCuentaDialog.tsx) resuelve los
--   tipos por NOMBRE, no por id, precisamente porque Preview y Produccion no garantizan la
--   misma numeracion — confirmado: Preview tiene 63 filas con ids 1-63 y produccion tiene
--   60 filas con max(id) = 65.
--
-- ─── Los nombres son el contrato con el front ─────────────────────────────────
-- Deben coincidir EXACTAMENTE con la constante TIPOS_DOCUMENTO_CUENTA del front, acentos
-- incluidos. Por eso esta migracion es self-verifying: si tras el INSERT no aparecen los
-- tres nombres exactos, aborta. Un archivo mal codificado insertaria nombres corruptos, el
-- front no los encontraria y el modal seguiria mostrando el aviso de "pendientes de alta"
-- sin que el deploy fallara ni nadie se enterara.
--
-- Idempotente: ON CONFLICT (nombre) DO NOTHING sobre la constraint tipos_documento_nombre_key,
-- que ya existe en la tabla. Sin BEGIN/COMMIT (el CI envuelve cada archivo).

-- ═══════════════════════════════════════════════════════════════════════════════
-- 1. Alta de los tres tipos
-- ═══════════════════════════════════════════════════════════════════════════════
INSERT INTO public.tipos_documento (nombre, padre, asignado_a, id_categoria_documento, activo)
VALUES
  ('Nota de crédito',                         'p', 'prop', 4, true),
  ('Evidencia de devolución',                 'p', 'prop', 8, true),
  ('Comprobante de transferencia al cliente', 'p', 'prop', 8, true)
ON CONFLICT (nombre) DO NOTHING;

-- ═══════════════════════════════════════════════════════════════════════════════
-- 2. Guard self-verifying: los tres nombres exactos deben existir y estar activos
-- ═══════════════════════════════════════════════════════════════════════════════
DO $guard$
DECLARE
  v_faltantes text;
  v_ids       text;
BEGIN
  SELECT string_agg(n.nombre, ', ' ORDER BY n.nombre)
  INTO v_faltantes
  FROM (VALUES
    ('Nota de crédito'),
    ('Evidencia de devolución'),
    ('Comprobante de transferencia al cliente')
  ) AS n(nombre)
  WHERE NOT EXISTS (
    SELECT 1 FROM public.tipos_documento t
    WHERE t.nombre = n.nombre AND t.activo
  );

  IF v_faltantes IS NOT NULL THEN
    RAISE EXCEPTION
      'No quedaron dados de alta (o quedaron inactivos) estos tipos de documento: %. El front los resuelve por nombre exacto, asi que el catalogo quedaria inservible. Revisar la codificacion del archivo de migracion.',
      v_faltantes;
  END IF;

  SELECT string_agg(format('%s=%s', t.nombre, t.id), ', ' ORDER BY t.id)
  INTO v_ids
  FROM public.tipos_documento t
  WHERE t.nombre IN ('Nota de crédito',
                     'Evidencia de devolución',
                     'Comprobante de transferencia al cliente');

  RAISE NOTICE 'Tipos de documento de cancelacion dados de alta: %.', v_ids;
END
$guard$;

-- ─── Validación (post-deploy, read-only) ──────────────────────────────────────
-- Los cinco tipos del modal existen y estan activos:
--   SELECT id, nombre, padre, asignado_a, id_categoria_documento, activo
--   FROM public.tipos_documento
--   WHERE nombre IN ('Nota de crédito',
--                    'Evidencia de devolución',
--                    'Comprobante de transferencia al cliente',
--                    'Factura XML',
--                    'Factura PDF')
--   ORDER BY id;
--   -- esperado: 5 filas, todas con activo = true
--
-- Sin duplicados (la constraint UNIQUE (nombre) ya lo impide, queda como aserto):
--   SELECT nombre, count(*) FROM public.tipos_documento
--   WHERE nombre IN ('Nota de crédito',
--                    'Evidencia de devolución',
--                    'Comprobante de transferencia al cliente')
--   GROUP BY nombre HAVING count(*) > 1;
--   -- esperado: 0 filas
--
-- Ninguno cayo en la categoria 7, que alimenta "Documentos de entrega faltantes":
--   SELECT count(*) AS en_categoria_7 FROM public.tipos_documento
--   WHERE id_categoria_documento = 7
--     AND nombre IN ('Nota de crédito',
--                    'Evidencia de devolución',
--                    'Comprobante de transferencia al cliente');
--   -- esperado: 0
--
-- ─── Resultado esperado ───────────────────────────────────────────────────────
-- · El selector del modal "Agregar documentos" lista las 5 opciones y desaparece el aviso
--   de "Tipos de documento pendientes de dar de alta en el catalogo".
-- · Los documentos cargados quedan en public.documentos con id_cuenta_cobranza de la
--   cuenta, id_producto (cuentas de producto) o id_propiedad (cuentas de propiedad),
--   id_estatus_verificacion = 1 (Pendiente) y activo = true.
-- · Aparecen en la pestania Documentos del detalle, en "Documentos de la Cuenta"
--   (productos) o "Documentos de la Propiedad".
-- · Al ir en categorias 4 y 8, NO alteran el bloque "Documentos de entrega faltantes",
--   que solo mira la categoria 7 y solo aplica a cuentas de propiedad.
--
-- Mientras este DML no se ejecute el modal sigue funcionando: muestra solo Factura
-- XML/PDF y un aviso con los tipos pendientes de alta.
