-- Normalización: entregas_checklist_items.estatus (TEXT) → id_estatus_checklist (FK).
-- Fecha: 2026-06-16  ·  v4 — catálogo sin columna `clave`, con DROP de la legacy.
--
-- Catálogo estatus_checklist de 8 estatus; la fuente de verdad es el id numérico
-- (sin columna `clave`). Migra los datos, aplica FK + índice y ELIMINA la columna
-- legacy `estatus` (con su CHECK y DEFAULT) tras triple validación.
--
-- ⚠️ DESTRUCTIVO: el PASO 10 hace DROP COLUMN estatus. Aplicar en prod SOLO cuando el
-- frontend/backend ya referencien id_estatus_checklist (no item.estatus texto), o el
-- portal de entregas se romperá. En dev: catálogo/columna nuevas no existen, estatus
-- legacy existe con 75 filas PENDIENTE → migran a id 1.
--
-- NO elimina registros de negocio (sin DELETE/TRUNCATE/DROP TABLE). Idempotente
-- (IF NOT EXISTS / ON CONFLICT / DO-blocks / EXECUTE dinámico tras el DROP).
-- No toca constraints de entregas_checklist_categorias ni entregas.

BEGIN;

-- PASO 1: catálogo (id numérico como fuente de verdad, sin columna clave)
CREATE TABLE IF NOT EXISTS public.estatus_checklist (
  id                  INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre              VARCHAR(120)  NOT NULL,
  descripcion         TEXT,
  activo              BOOLEAN       NOT NULL DEFAULT true,
  fecha_creacion      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  fecha_actualizacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.estatus_checklist IS
  'Catálogo de estatus para ítems del checklist de entrega. Fuente de verdad: id '
  'numérico, sin columna clave. El frontend referencia por id, no por texto.';

-- PASO 2: poblar 8 estatus (idempotente)
INSERT INTO public.estatus_checklist (id, nombre, descripcion) VALUES
  (1, 'Pendiente',               'Ítem pendiente de revisión por el equipo de entregas'),
  (2, 'Cumple',                  'El ítem cumple los requisitos de entrega (absorbe legacy: COMPLETADO)'),
  (3, 'No cumple',               'El ítem no cumple los requisitos — requiere atención o reparación (absorbe legacy: CON_OBSERVACION)'),
  (4, 'No aplica',               'El ítem no aplica para esta unidad'),
  (5, 'En reparación',           'El ítem está en proceso de reparación activa'),
  (6, 'Reparado pendiente VoBo', 'Reparación completada, pendiente de visto bueno del supervisor'),
  (7, 'VoBo aprobado',           'Visto bueno aprobado — ítem cerrado satisfactoriamente'),
  (8, 'VoBo rechazado',          'Visto bueno rechazado — requiere nueva reparación')
ON CONFLICT (id) DO UPDATE
  SET nombre              = EXCLUDED.nombre,
      descripcion         = EXCLUDED.descripcion,
      activo              = true,
      fecha_actualizacion = now();

-- Sincronizar la secuencia IDENTITY tras el seed con ids explícitos (1-8),
-- para que futuros inserts sin id arranquen en 9.
SELECT setval(
  pg_get_serial_sequence('public.estatus_checklist', 'id'),
  (SELECT MAX(id) FROM public.estatus_checklist)
);

-- PASO 3: columna nueva
ALTER TABLE public.entregas_checklist_items
  ADD COLUMN IF NOT EXISTS id_estatus_checklist INTEGER;

-- PASO 4: migrar (EXECUTE dinámico → no falla si `estatus` ya fue eliminada)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='entregas_checklist_items' AND column_name='estatus'
  ) THEN
    EXECUTE $migration$
      UPDATE public.entregas_checklist_items
      SET id_estatus_checklist = CASE estatus
        WHEN 'PENDIENTE'                THEN 1
        WHEN 'COMPLETADO'               THEN 2
        WHEN 'CUMPLE'                   THEN 2
        WHEN 'CON_OBSERVACION'          THEN 3
        WHEN 'CON OBSERVACION'          THEN 3
        WHEN 'CON OBSERVACIÓN'          THEN 3
        WHEN 'NO_CUMPLE'                THEN 3
        WHEN 'NO CUMPLE'                THEN 3
        WHEN 'NO_APLICA'                THEN 4
        WHEN 'NO APLICA'                THEN 4
        WHEN 'EN_REPARACION'            THEN 5
        WHEN 'EN REPARACION'            THEN 5
        WHEN 'EN REPARACIÓN'            THEN 5
        WHEN 'REPARADO_PENDIENTE_VOBO'  THEN 6
        WHEN 'REPARADO PENDIENTE VOBO'  THEN 6
        WHEN 'VOBO_APROBADO'            THEN 7
        WHEN 'VOBO APROBADO'            THEN 7
        WHEN 'VOBO_RECHAZADO'           THEN 8
        WHEN 'VOBO RECHAZADO'           THEN 8
        ELSE NULL
      END
      WHERE id_estatus_checklist IS NULL;
    $migration$;
  END IF;
END $$;

-- PASO 5: abortar si quedaron NULLs (estatus fuera del CASE)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM public.entregas_checklist_items WHERE id_estatus_checklist IS NULL) THEN
    RAISE EXCEPTION
      E'MIGRACIÓN INCOMPLETA — ítems con id_estatus_checklist NULL.\n'
      'Diagnóstico: SELECT estatus, COUNT(*) FROM entregas_checklist_items '
      'WHERE id_estatus_checklist IS NULL GROUP BY estatus;';
  END IF;
END $$;

-- PASO 6 + 7: NOT NULL + DEFAULT 1
ALTER TABLE public.entregas_checklist_items
  ALTER COLUMN id_estatus_checklist SET NOT NULL;
ALTER TABLE public.entregas_checklist_items
  ALTER COLUMN id_estatus_checklist SET DEFAULT 1;

-- PASO 8: FK (idempotente)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_type='FOREIGN KEY' AND table_schema='public'
      AND table_name='entregas_checklist_items' AND constraint_name='fk_checklist_items_estatus'
  ) THEN
    ALTER TABLE public.entregas_checklist_items
      ADD CONSTRAINT fk_checklist_items_estatus
      FOREIGN KEY (id_estatus_checklist) REFERENCES public.estatus_checklist(id);
  END IF;
END $$;

-- PASO 9: índice
CREATE INDEX IF NOT EXISTS idx_checklist_items_estatus
  ON public.entregas_checklist_items(id_estatus_checklist);

-- PASO 10: validar (columna nueva existe, sin NULLs, FK activa) y eliminar legacy.
-- El DROP COLUMN elimina también su CHECK y DEFAULT automáticamente.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='entregas_checklist_items' AND column_name='id_estatus_checklist') THEN
    RAISE EXCEPTION 'VALIDACIÓN (1/3): falta columna id_estatus_checklist; no se elimina estatus.';
  END IF;
  IF EXISTS (SELECT 1 FROM public.entregas_checklist_items WHERE id_estatus_checklist IS NULL) THEN
    RAISE EXCEPTION 'VALIDACIÓN (2/3): hay id_estatus_checklist NULL; migración incompleta.';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_type='FOREIGN KEY' AND table_schema='public'
      AND table_name='entregas_checklist_items' AND constraint_name='fk_checklist_items_estatus') THEN
    RAISE EXCEPTION 'VALIDACIÓN (3/3): falta FK fk_checklist_items_estatus.';
  END IF;
END $$;

ALTER TABLE public.entregas_checklist_items
  DROP COLUMN IF EXISTS estatus;

COMMIT;
