-- ============================================================
-- Rate limit para reset-user-password (modo público)
-- Acota griefing/DoS: el endpoint público es anónimo y en cada
-- request des-confirma el correo + fija Temporal123!. Sin límite,
-- cualquiera que sepa un correo puede bloquear la cuenta a voluntad
-- y spamear correos. Esta tabla registra intentos por email/ip.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.password_reset_intentos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text,
  ip text,
  fecha_creacion timestamp with time zone DEFAULT now() NOT NULL
);

-- Consultas de conteo por email/ip en ventana reciente.
CREATE INDEX IF NOT EXISTS idx_password_reset_intentos_email_fecha
  ON public.password_reset_intentos (email, fecha_creacion DESC);
CREATE INDEX IF NOT EXISTS idx_password_reset_intentos_ip_fecha
  ON public.password_reset_intentos (ip, fecha_creacion DESC);

-- Solo la edge function (service role) la toca. RLS ON, sin políticas
-- => anon/authenticated no leen ni escriben; service role la ignora (bypass).
ALTER TABLE public.password_reset_intentos ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.password_reset_intentos IS
  'Bitacora de intentos de reset de contrasena (modo publico) para rate limiting. Escrita por edge function reset-user-password con service role.';
