-- Portal Tickets de Seguimiento — Chat interno de atención (Fase 4).
--
-- Chat en tiempo real DENTRO de un ticket, SOLO para staff interno: el creador
-- (tickets.id_usuario_creador) y los propietarios (tickets_propietarios + el legacy
-- tickets.id_usuario_propietario). El solicitante NO entra en esta fase.
--
-- 2 tablas:
--   * tickets_chat_participantes — quién se unió al chat de un ticket (presencia-por-fila:
--     INSERT al unirse, DELETE al salir; sin `activo`). Molde: tickets_propietarios.
--   * tickets_chat_mensajes — log append-only de los mensajes (todo se documenta; sin
--     UPDATE/DELETE para conservar el historial del caso).
--
-- Realtime (Supabase): ambas tablas se exponen al canal `supabase_realtime` para que el
-- front reciba mensajes y uniones al instante. CRÍTICO: Realtime RESPETA RLS — si la RLS no
-- acota por pertenencia, los cambios se difundirían a TODOS los suscriptores (fuga). Por eso:
--   - los MENSAJES solo son visibles/insertables por PARTICIPANTES del ticket (o admin), y
--   - unirse / ver participantes solo lo pueden los STAKEHOLDERS del ticket
--     (creador o propietarios) o admin.
--
-- Idempotente (IF NOT EXISTS, DROP POLICY IF EXISTS + CREATE, guard en la publicación,
-- ENABLE RLS re-ejecutable). Sin BEGIN/COMMIT (el CI/CD lo envuelve en transacción).
-- Corre en Preview y Producción.

-- ─────────────────────────────────────────────────────────────────────────────
-- 1) Tablas
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.tickets_chat_participantes (
    id           INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ticket    INTEGER      NOT NULL REFERENCES public.tickets(id) ON DELETE CASCADE,
    id_usuario   UUID         NOT NULL,   -- auth_user_id del participante (staff interno)
    fecha_union  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_tickets_chat_participantes UNIQUE (id_ticket, id_usuario)
);
CREATE INDEX IF NOT EXISTS idx_tickets_chat_part_ticket  ON public.tickets_chat_participantes (id_ticket);
CREATE INDEX IF NOT EXISTS idx_tickets_chat_part_usuario ON public.tickets_chat_participantes (id_usuario);

CREATE TABLE IF NOT EXISTS public.tickets_chat_mensajes (
    id              INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ticket       INTEGER      NOT NULL REFERENCES public.tickets(id) ON DELETE CASCADE,
    id_autor        UUID         NOT NULL,   -- auth_user_id de quien escribió
    texto           TEXT         NOT NULL,
    fecha_creacion  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_tickets_chat_msj_ticket ON public.tickets_chat_mensajes (id_ticket, fecha_creacion);

-- ─────────────────────────────────────────────────────────────────────────────
-- 2) Realtime: exponer ambas tablas (guard: ADD TABLE falla si ya es miembro)
-- ─────────────────────────────────────────────────────────────────────────────
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public'
      AND tablename = 'tickets_chat_mensajes'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.tickets_chat_mensajes;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public'
      AND tablename = 'tickets_chat_participantes'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.tickets_chat_participantes;
  END IF;
END $$;

-- ─────────────────────────────────────────────────────────────────────────────
-- 3) RLS
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.tickets_chat_participantes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tickets_chat_mensajes      ENABLE ROW LEVEL SECURITY;

-- Participantes: ver / unirse solo si eres stakeholder (creador o propietario) del ticket, o
-- admin. Insertas SOLO tu propia fila (te unes a ti mismo). Sales tú mismo (o admin te quita).
DO $$
BEGIN
  DROP POLICY IF EXISTS tickets_chat_part_select ON public.tickets_chat_participantes;
  DROP POLICY IF EXISTS tickets_chat_part_insert ON public.tickets_chat_participantes;
  DROP POLICY IF EXISTS tickets_chat_part_delete ON public.tickets_chat_participantes;

  CREATE POLICY tickets_chat_part_select ON public.tickets_chat_participantes
    FOR SELECT TO authenticated
    USING (
      is_admin_user()
      OR id_usuario = auth.uid()
      OR EXISTS (
        SELECT 1 FROM public.tickets t
        WHERE t.id = tickets_chat_participantes.id_ticket
          AND (t.id_usuario_creador = auth.uid() OR t.id_usuario_propietario = auth.uid())
      )
      OR EXISTS (
        SELECT 1 FROM public.tickets_propietarios tp
        WHERE tp.id_ticket = tickets_chat_participantes.id_ticket AND tp.id_usuario = auth.uid()
      )
    );

  CREATE POLICY tickets_chat_part_insert ON public.tickets_chat_participantes
    FOR INSERT TO authenticated
    WITH CHECK (
      id_usuario = auth.uid()
      AND (
        is_admin_user()
        OR EXISTS (
          SELECT 1 FROM public.tickets t
          WHERE t.id = tickets_chat_participantes.id_ticket
            AND (t.id_usuario_creador = auth.uid() OR t.id_usuario_propietario = auth.uid())
        )
        OR EXISTS (
          SELECT 1 FROM public.tickets_propietarios tp
          WHERE tp.id_ticket = tickets_chat_participantes.id_ticket AND tp.id_usuario = auth.uid()
        )
      )
    );

  CREATE POLICY tickets_chat_part_delete ON public.tickets_chat_participantes
    FOR DELETE TO authenticated
    USING (is_admin_user() OR id_usuario = auth.uid());
END $$;

-- Mensajes: SOLO participantes del ticket (o admin) los VEN → esto acota el Realtime a los
-- del chat. Insertas como tú mismo y solo si eres participante. Sin UPDATE/DELETE = inmutable
-- (todo queda documentado).
DO $$
BEGIN
  DROP POLICY IF EXISTS tickets_chat_msj_select ON public.tickets_chat_mensajes;
  DROP POLICY IF EXISTS tickets_chat_msj_insert ON public.tickets_chat_mensajes;

  CREATE POLICY tickets_chat_msj_select ON public.tickets_chat_mensajes
    FOR SELECT TO authenticated
    USING (
      is_admin_user()
      OR EXISTS (
        SELECT 1 FROM public.tickets_chat_participantes p
        WHERE p.id_ticket = tickets_chat_mensajes.id_ticket AND p.id_usuario = auth.uid()
      )
    );

  CREATE POLICY tickets_chat_msj_insert ON public.tickets_chat_mensajes
    FOR INSERT TO authenticated
    WITH CHECK (
      id_autor = auth.uid()
      AND EXISTS (
        SELECT 1 FROM public.tickets_chat_participantes p
        WHERE p.id_ticket = tickets_chat_mensajes.id_ticket AND p.id_usuario = auth.uid()
      )
    );
END $$;
