-- 20260625020000_facturas_mantenimientos.sql
-- Propósito: habilitar el registro de facturación (Facturapi) de los pagos de
-- mantenimiento. Cada fila vincula un pago (public.pagos) con su factura emitida,
-- guardando las URLs de PDF/XML y el flag de facturado. Un pago se factura una sola vez
-- (UNIQUE id_pago). La emisión la realiza la edge function generar-factura-mantenimiento.

CREATE TABLE IF NOT EXISTS public.facturas_mantenimientos (
  id                    integer GENERATED BY DEFAULT AS IDENTITY,
  id_pago               integer NOT NULL,
  facturado             boolean NOT NULL DEFAULT false,
  url_factura_pdf       text NULL,
  url_factura_xml       text NULL,
  fecha_creacion        timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_actualizacion   timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT facturas_mantenimientos_pkey PRIMARY KEY (id),
  CONSTRAINT facturas_mantenimientos_id_pago_fkey
    FOREIGN KEY (id_pago) REFERENCES public.pagos(id),
  CONSTRAINT facturas_mantenimientos_id_pago_key UNIQUE (id_pago)
);

-- Trigger de fecha_actualizacion: reutiliza la función existente del baseline
-- (public.update_updated_at_column), mismo patrón que public.pagos.
DROP TRIGGER IF EXISTS update_facturas_mantenimientos_updated_at ON public.facturas_mantenimientos;
CREATE TRIGGER update_facturas_mantenimientos_updated_at
  BEFORE UPDATE ON public.facturas_mantenimientos
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
