-- Esquema Estados de Cuenta SOZU: cuentas_sozu + estados_cuenta + bucket + RLS.
-- Fecha: 2026-06-18
--
-- cuentas_sozu: cuentas bancarias propias de SOZU (alias = slug de carpeta en Storage).
-- estados_cuenta: registro de estados de cuenta subidos al bucket `estados_cuenta`
--   (ruta {proyecto}/{banco}/{alias}/{anio}/{archivo}). id_banco NO se desnormaliza
--   aquí (se obtiene vía cuentas_sozu→bancos). UNIQUE por cuenta×año×mes.
-- NO usa cuentas_bancarias (es de personas) ni documentos (otro dominio).
--
-- Correcciones vs el spec (verificado en dev):
--   * RLS de escritura usaba usuarios.id_auth → la columna real es auth_user_id.
--   * Triggers con DROP TRIGGER IF EXISTS para idempotencia (el spec no las tenía).
--   * Bucket: no existe en dev → se crea (público, coherente con las URLs /object/public/).
-- set_fecha_actualizacion ya existe en dev.

-- ── 1. cuentas_sozu ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.cuentas_sozu (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_banco            INTEGER NOT NULL REFERENCES public.bancos(id),
  alias               TEXT    NOT NULL,
  numero_cuenta       TEXT,
  clabe               TEXT,
  activo              BOOLEAN     NOT NULL DEFAULT TRUE,
  fecha_creacion      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  public.cuentas_sozu       IS 'Cuentas bancarias propias de SOZU para recaudación y conciliación.';
COMMENT ON COLUMN public.cuentas_sozu.alias IS 'Slug usado como carpeta en el bucket estados_cuenta: {proyecto}/{banco}/{alias}/{anio}/';

CREATE INDEX IF NOT EXISTS idx_cuentas_sozu_banco ON public.cuentas_sozu(id_banco) WHERE activo;

DROP TRIGGER IF EXISTS trg_fecha_actualizacion_cuentas_sozu ON public.cuentas_sozu;
CREATE TRIGGER trg_fecha_actualizacion_cuentas_sozu
  BEFORE UPDATE ON public.cuentas_sozu
  FOR EACH ROW EXECUTE FUNCTION public.set_fecha_actualizacion();

-- ── 2. estados_cuenta ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.estados_cuenta (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_proyecto         INTEGER  NOT NULL REFERENCES public.proyectos(id),
  id_cuenta_sozu      BIGINT   NOT NULL REFERENCES public.cuentas_sozu(id),
  anio                SMALLINT NOT NULL CHECK (anio BETWEEN 2020 AND 2040),
  mes                 SMALLINT NOT NULL CHECK (mes BETWEEN 1 AND 12),
  url_estado_cuenta   TEXT     NOT NULL,
  nombre_archivo      TEXT,
  subido_por          TEXT,
  activo              BOOLEAN     NOT NULL DEFAULT TRUE,
  fecha_creacion      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_estado_cuenta_por_mes UNIQUE (id_cuenta_sozu, anio, mes)
);

COMMENT ON TABLE  public.estados_cuenta                   IS 'Estados de cuenta bancarios de SOZU. Un archivo por cuenta-banco por mes.';
COMMENT ON COLUMN public.estados_cuenta.url_estado_cuenta IS 'Ruta relativa en bucket estados_cuenta. URL pública = storage_url/object/public/estados_cuenta/{url_estado_cuenta}';
COMMENT ON COLUMN public.estados_cuenta.subido_por        IS 'Email del usuario que subió el archivo (TEXT).';

CREATE INDEX IF NOT EXISTS idx_estados_cuenta_proyecto ON public.estados_cuenta(id_proyecto)    WHERE activo;
CREATE INDEX IF NOT EXISTS idx_estados_cuenta_anio_mes ON public.estados_cuenta(anio, mes);
CREATE INDEX IF NOT EXISTS idx_estados_cuenta_cuenta   ON public.estados_cuenta(id_cuenta_sozu) WHERE activo;

DROP TRIGGER IF EXISTS trg_fecha_actualizacion_estados_cuenta ON public.estados_cuenta;
CREATE TRIGGER trg_fecha_actualizacion_estados_cuenta
  BEFORE UPDATE ON public.estados_cuenta
  FOR EACH ROW EXECUTE FUNCTION public.set_fecha_actualizacion();

-- ── 3. Bucket estados_cuenta (público) + RLS ─────────────────
INSERT INTO storage.buckets (id, name, public)
VALUES ('estados_cuenta', 'estados_cuenta', true)
ON CONFLICT (id) DO UPDATE SET public = EXCLUDED.public;

-- Lectura: usuarios autenticados (acceso vía API; la URL /object/public ya es pública)
DROP POLICY IF EXISTS "Lectura estados_cuenta autenticados" ON storage.objects;
CREATE POLICY "Lectura estados_cuenta autenticados"
ON storage.objects FOR SELECT TO authenticated
USING (bucket_id = 'estados_cuenta');

-- Escritura: solo Super Admin (rol 1) y Admin Cobranza (rol 2)
DROP POLICY IF EXISTS "Subida estados_cuenta admins" ON storage.objects;
CREATE POLICY "Subida estados_cuenta admins"
ON storage.objects FOR INSERT TO authenticated
WITH CHECK (
  bucket_id = 'estados_cuenta'
  AND (SELECT rol_id FROM public.usuarios WHERE auth_user_id = auth.uid()) IN (1, 2)
);
