-- Módulo de Negocios (deals) del CRM, estilo HubSpot.
--
-- Modelo (aclarado por ventas / Manuel Nava):
--   * Un "pipeline" en SOZU = la LÍNEA DE NEGOCIO / "a qué se refiere" el negocio.
--     Se elige al crear el negocio. Ej.: "Inquilinos", "Daiku" (proyecto), "Mobtura
--     Muebles" (venta de muebles). Sirve para tener listados de negocios por línea.
--   * Cada pipeline tiene su propio embudo de ETAPAS (stages).
--   * Un pipeline puede -opcionalmente- mapear a un proyecto SOZU real (Daiku);
--     otros no (Mobtura Muebles) -> por eso id_proyecto vive en el pipeline, nullable.
--   * Un "contacto" del CRM = fila de `entidades_relacionadas` (prospecto 7 / comprador 2).
--     Un negocio se asocia a N contactos vía `crm_negocios_contactos`.

-- ─── crm_pipelines ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.crm_pipelines (
    id              INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          TEXT         NOT NULL,
    id_proyecto     INTEGER      REFERENCES public.proyectos(id) ON DELETE SET NULL, -- opcional
    orden           INTEGER      NOT NULL DEFAULT 100,
    activo          BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_crm_pipelines_proyecto ON public.crm_pipelines (id_proyecto);

-- ─── crm_pipeline_etapas ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.crm_pipeline_etapas (
    id              INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pipeline     INTEGER      NOT NULL
        REFERENCES public.crm_pipelines(id) ON DELETE CASCADE,
    nombre          TEXT         NOT NULL,
    orden           INTEGER      NOT NULL DEFAULT 100,
    probabilidad    NUMERIC(5,2) NOT NULL DEFAULT 0,   -- 0..100 (%)
    es_ganado       BOOLEAN      NOT NULL DEFAULT FALSE, -- etapa de cierre ganado
    es_perdido      BOOLEAN      NOT NULL DEFAULT FALSE, -- etapa de cierre perdido
    activo          BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_crm_pipeline_etapas_pipeline ON public.crm_pipeline_etapas (id_pipeline);

-- ─── crm_negocios ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.crm_negocios (
    id                      INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre                  TEXT         NOT NULL,
    id_pipeline             INTEGER      NOT NULL
        REFERENCES public.crm_pipelines(id),
    id_etapa                INTEGER      NOT NULL
        REFERENCES public.crm_pipeline_etapas(id),
    valor                   NUMERIC(14,2),               -- opcional
    moneda                  TEXT         NOT NULL DEFAULT 'MXN',
    id_usuario_propietario  UUID,                        -- auth_user_id del propietario
    fecha_cierre_estimada   DATE,
    activo                  BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    fecha_actualizacion     TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_crm_negocios_pipeline    ON public.crm_negocios (id_pipeline);
CREATE INDEX IF NOT EXISTS idx_crm_negocios_etapa       ON public.crm_negocios (id_etapa);
CREATE INDEX IF NOT EXISTS idx_crm_negocios_propietario ON public.crm_negocios (id_usuario_propietario);

-- Trigger fecha_actualizacion automática
CREATE OR REPLACE FUNCTION public.set_crm_negocios_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.fecha_actualizacion = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_crm_negocios_updated_at ON public.crm_negocios;
CREATE TRIGGER trg_crm_negocios_updated_at
BEFORE UPDATE ON public.crm_negocios
FOR EACH ROW EXECUTE FUNCTION public.set_crm_negocios_updated_at();

-- ─── crm_negocios_contactos (M:N negocio ↔ contacto) ──────────────────────────
CREATE TABLE IF NOT EXISTS public.crm_negocios_contactos (
    id                      INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_negocio              INTEGER      NOT NULL
        REFERENCES public.crm_negocios(id) ON DELETE CASCADE,
    id_entidad_relacionada  BIGINT       NOT NULL
        REFERENCES public.entidades_relacionadas(id) ON DELETE CASCADE,
    rol                     TEXT,                        -- rol del contacto en el negocio (opcional)
    es_principal            BOOLEAN      NOT NULL DEFAULT FALSE,
    activo                  BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_crm_negocios_contactos UNIQUE (id_negocio, id_entidad_relacionada)
);

CREATE INDEX IF NOT EXISTS idx_crm_neg_cont_negocio ON public.crm_negocios_contactos (id_negocio);
CREATE INDEX IF NOT EXISTS idx_crm_neg_cont_er      ON public.crm_negocios_contactos (id_entidad_relacionada);

-- ─── Row Level Security ───────────────────────────────────────────────────────
-- Datos internos del equipo de ventas: lectura/escritura autenticados, borrado admin.
ALTER TABLE public.crm_pipelines           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crm_pipeline_etapas     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crm_negocios            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crm_negocios_contactos  ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
    t TEXT;
BEGIN
    FOREACH t IN ARRAY ARRAY['crm_pipelines','crm_pipeline_etapas','crm_negocios','crm_negocios_contactos']
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', t || '_select', t);
        EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', t || '_insert', t);
        EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', t || '_update', t);
        EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', t || '_delete', t);

        EXECUTE format('CREATE POLICY %I ON public.%I FOR SELECT TO authenticated USING (true)', t || '_select', t);
        EXECUTE format('CREATE POLICY %I ON public.%I FOR INSERT TO authenticated WITH CHECK (true)', t || '_insert', t);
        EXECUTE format('CREATE POLICY %I ON public.%I FOR UPDATE TO authenticated USING (true) WITH CHECK (true)', t || '_update', t);
        EXECUTE format('CREATE POLICY %I ON public.%I FOR DELETE TO authenticated USING (is_admin_user())', t || '_delete', t);
    END LOOP;
END;
$$;

-- ─── Seed: pipeline "Inquilinos" + etapas (ejemplo real de HubSpot) ───────────
-- Idempotente: solo inserta lo que falte (por nombre). Pendiente sembrar Daiku /
-- Mobtura Muebles cuando ventas confirme sus etapas.
INSERT INTO public.crm_pipelines (nombre, orden, activo)
SELECT 'Inquilinos', 10, TRUE
WHERE NOT EXISTS (SELECT 1 FROM public.crm_pipelines WHERE nombre = 'Inquilinos');

INSERT INTO public.crm_pipeline_etapas (id_pipeline, nombre, orden, probabilidad, es_ganado, es_perdido, activo)
SELECT p.id, v.nombre, v.orden, v.prob, v.ganado, v.perdido, TRUE
FROM public.crm_pipelines p
CROSS JOIN (VALUES
    ('Nuevo lead',                   10,  10, FALSE, FALSE),
    ('Viendo',                       20,  40, FALSE, FALSE),
    ('Depósito de seguridad pagado', 30,  80, FALSE, FALSE),
    ('Cierre ganado',                40, 100, TRUE,  FALSE),
    ('Cierre perdido',               50,   0, FALSE, TRUE)
) AS v(nombre, orden, prob, ganado, perdido)
WHERE p.nombre = 'Inquilinos'
  AND NOT EXISTS (
    SELECT 1 FROM public.crm_pipeline_etapas e
    WHERE e.id_pipeline = p.id AND e.nombre = v.nombre
  );
