-- Análisis de IA por negocio (Asistente IA de ventas — Fase 1).
-- Fecha: 2026-08-17
--
-- Guarda el ÚLTIMO análisis generado por la Edge Function `analizar-negocio-ia` (Claude) para
-- cada negocio (1:1 con crm_negocios): perfil del cliente, % de cierre, justificación, nota de
-- bitácora, borrador de WhatsApp y próximo paso sugerido (tipo + fecha/hora + razonamiento).
-- Alimenta el badge del Kanban (fecha/canal del próximo seguimiento) y el desglose en la ficha.
--
-- RLS espejo de crm_citas: authenticated lee/crea/actualiza; borrado duro solo admin.
-- Idempotente y self-guarded. Sin BEGIN/COMMIT (el CI/CD envuelve en tx).

CREATE TABLE IF NOT EXISTS public.crm_negocios_ia (
    id                    INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_negocio            INTEGER     NOT NULL UNIQUE
        REFERENCES public.crm_negocios(id) ON DELETE CASCADE,  -- 1:1 con el negocio
    perfil_cliente        TEXT,        -- p. ej. Inversionista, Emocional, Comprador final, Analítico/Financiero
    probabilidad_cierre   SMALLINT    CHECK (probabilidad_cierre BETWEEN 0 AND 100),
    justificacion         TEXT,        -- razonamiento anti-sesgo del %
    nota_generada         TEXT,        -- nota de bitácora propuesta por la IA
    whatsapp_borrador     TEXT,        -- borrador de mensaje de seguimiento
    proximo_tipo          TEXT,        -- 'llamada' | 'mensaje'
    proximo_fecha         TIMESTAMPTZ, -- fecha/hora sugerida del próximo contacto
    proximo_razonamiento  TEXT,        -- por qué esa acción/fecha/hora
    contexto_input        TEXT,        -- texto capturado por el asesor (para referencia)
    modelo                TEXT,        -- modelo Claude usado
    generado_por          UUID,        -- auth_user_id del asesor que corrió el análisis
    fecha_generacion      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    activo                BOOLEAN     NOT NULL DEFAULT TRUE,
    fecha_creacion        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_crm_negocios_ia_negocio
    ON public.crm_negocios_ia (id_negocio);
CREATE INDEX IF NOT EXISTS idx_crm_negocios_ia_proximo_fecha
    ON public.crm_negocios_ia (proximo_fecha);

-- Trigger fecha_actualizacion: reutiliza la función compartida.
DROP TRIGGER IF EXISTS trg_crm_negocios_ia_fecha_actualizacion ON public.crm_negocios_ia;
CREATE TRIGGER trg_crm_negocios_ia_fecha_actualizacion
BEFORE UPDATE ON public.crm_negocios_ia
FOR EACH ROW EXECUTE FUNCTION public.crm_set_fecha_actualizacion();

-- ─── Row Level Security (espejo de crm_citas) ─────────────────────────────────
ALTER TABLE public.crm_negocios_ia ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "crm_negocios_ia_select" ON public.crm_negocios_ia;
CREATE POLICY "crm_negocios_ia_select" ON public.crm_negocios_ia
    FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "crm_negocios_ia_insert" ON public.crm_negocios_ia;
CREATE POLICY "crm_negocios_ia_insert" ON public.crm_negocios_ia
    FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "crm_negocios_ia_update" ON public.crm_negocios_ia;
CREATE POLICY "crm_negocios_ia_update" ON public.crm_negocios_ia
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "crm_negocios_ia_delete" ON public.crm_negocios_ia;
CREATE POLICY "crm_negocios_ia_delete" ON public.crm_negocios_ia
    FOR DELETE TO authenticated USING (public.is_admin_user());

COMMENT ON TABLE public.crm_negocios_ia IS
  'Último análisis de IA (Claude) por negocio (1:1 con crm_negocios): perfil, % cierre, nota, borrador WhatsApp y próximo paso. Generado por la Edge Function analizar-negocio-ia.';
