-- =============================================================================
-- personas_relacionadas: representante legal y accionistas (grafo recursivo)
-- =============================================================================
-- El expediente de persona moral necesita VARIOS representantes legales y VARIOS
-- accionistas mayoritarios con su porcentaje, y que el cliente los dé de alta desde el
-- portal. Si un accionista es persona moral, repite el flujo hasta llegar a personas
-- físicas (beneficiario controlador).
--
-- Hoy el modelo no lo permite: `personas.id_entidad_relacionada_rep_leg` es UNA columna,
-- o sea exactamente un vínculo (68 personas la usan hoy), y `entidades_relacionadas`
-- modela persona↔proyecto, no persona↔persona, y no tiene dónde poner el porcentaje.
--
-- El grafo recursivo NO necesita tabla aparte: una empresa que es accionista de otra es
-- otra fila, y sus propios vínculos cuelgan de ella igual que los de la primera.
--
-- ─── Verificado read-only el 2026-08-13 en prod (tzmhgfjmddkfyffkkmto) ────────
-- · `personas_relacionadas` no existe.
-- · `tipos_relacion` tiene 14 filas y está HUÉRFANO: ninguna tabla lo referencia por FK
--   desde que se creó. Esta migración es el primer consumidor.
-- · id 1 = 'Representante Legal' (tipo 'el'); no existe 'Accionista'.
-- · `tipos_relacion.id` es GENERATED BY DEFAULT AS IDENTITY → el INSERT sin id funciona.
-- · `personas.id` es integer; `tipo_persona` toma 'pf' y 'pm'.
-- · Las tablas nuevas del repo (solicitudes_propietario, crm_leads_atribucion,
--   roles_apps) usan timestamptz; se sigue esa convención.
-- · `set_fecha_actualizacion()` ya existe y la usan 57 triggers: se reutiliza.
-- · `user_has_internal_role()` y `current_persona_id()` existen.
--
-- ─── El id de 'Accionista' NO va a coincidir entre dev y prod ─────────────────
-- Igual que en la migración de anexos: los catálogos ya vienen desalineados. El backend
-- debe resolverlo por nombre, nunca cablear el número:
--   SELECT id FROM tipos_relacion WHERE nombre = 'Accionista'
--
-- ─── Fuera de alcance, a propósito ───────────────────────────────────────────
-- · Sin backfill: la tabla nace vacía. Copiar el rep legal que hoy vive en
--   `personas.id_entidad_relacionada_rep_leg` va en una migración aparte, cuando las
--   lecturas ya usen esta tabla. Hasta entonces la columna se queda.
-- · El umbral del 25% no va en la base: es regla de negocio, cambia por país o por ley,
--   y se aplica en la edge function y en la UI. La columna guarda el porcentaje real.
-- · Tampoco se valida que los porcentajes de una empresa sumen ≤ 100: un accionista
--   puede capturarse antes que los demás, así que el estado intermedio es legítimo.
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- §1. Catálogo: falta el tipo 'Accionista'
-- -----------------------------------------------------------------------------
-- 'Representante Legal' (id 1) ya existe y se reutiliza. `tipo = 'el'` es el mismo
-- valor que traen 'Representante Legal' y 'Empleado'.
-- `tipos_relacion` tiene UNIQUE (nombre), así que el ON CONFLICT hace la migración
-- idempotente y no tumba el CI si se reejecuta.
INSERT INTO public.tipos_relacion (nombre, activo, tipo)
VALUES ('Accionista', true, 'el')
ON CONFLICT (nombre) DO NOTHING;

-- -----------------------------------------------------------------------------
-- §2. La tabla de vínculo
-- -----------------------------------------------------------------------------
-- Es 3FN: no guarda nada de la persona ni del tipo, solo el vínculo y su único atributo
-- propio, `porcentaje`, que depende del vínculo entero. Lo desnormalizado es lo de hoy:
-- un rol cocido en una columna de `personas`.
CREATE TABLE IF NOT EXISTS public.personas_relacionadas (
  id                   bigserial    PRIMARY KEY,
  id_persona           integer      NOT NULL REFERENCES public.personas(id),
  id_persona_relacion  integer      NOT NULL REFERENCES public.personas(id),
  id_tipo_relacion     integer      NOT NULL REFERENCES public.tipos_relacion(id),
  porcentaje           numeric(5,2) NULL,
  activo               boolean      NOT NULL DEFAULT true,
  fecha_creacion       timestamptz  NOT NULL DEFAULT now(),
  fecha_actualizacion  timestamptz  NOT NULL DEFAULT now(),

  CONSTRAINT personas_relacionadas_unica
    UNIQUE (id_persona, id_persona_relacion, id_tipo_relacion),
  CONSTRAINT personas_relacionadas_no_autorreferencia
    CHECK (id_persona <> id_persona_relacion),
  CONSTRAINT personas_relacionadas_porcentaje_valido
    CHECK (porcentaje IS NULL OR (porcentaje > 0 AND porcentaje <= 100))
);

COMMENT ON TABLE public.personas_relacionadas IS
  'Vínculo persona↔persona del expediente: representantes legales y accionistas de una '
  'persona moral. Recursiva: si el accionista es PM, sus propios vínculos son otras filas.';
COMMENT ON COLUMN public.personas_relacionadas.id_persona IS
  'La empresa (persona moral) de la que cuelga el vínculo.';
COMMENT ON COLUMN public.personas_relacionadas.id_persona_relacion IS
  'El representante legal o accionista. Puede ser persona física o moral.';
COMMENT ON COLUMN public.personas_relacionadas.porcentaje IS
  'Porcentaje accionario. Solo aplica a accionistas; NULL para representante legal. '
  'El umbral del 25% es regla de negocio y NO se valida aquí.';
COMMENT ON COLUMN public.personas_relacionadas.activo IS
  'Baja lógica. Nunca se borra: los documentos de esa persona siguen colgando de ella.';

-- El UNIQUE no incluye `activo` a propósito: dar de baja y volver a agregar el mismo
-- vínculo es reactivar la fila existente (UPDATE activo = true), no insertar otra.
-- La edge function debe hacer upsert, no insert a ciegas.

CREATE INDEX IF NOT EXISTS idx_personas_relacionadas_persona_activo
  ON public.personas_relacionadas (id_persona, activo);

-- Para recorrer el árbol hacia arriba (de quién es accionista esta persona).
CREATE INDEX IF NOT EXISTS idx_personas_relacionadas_relacion
  ON public.personas_relacionadas (id_persona_relacion);

DROP TRIGGER IF EXISTS trg_personas_relacionadas_fecha ON public.personas_relacionadas;
CREATE TRIGGER trg_personas_relacionadas_fecha
  BEFORE UPDATE ON public.personas_relacionadas
  FOR EACH ROW EXECUTE FUNCTION public.set_fecha_actualizacion();

-- -----------------------------------------------------------------------------
-- §3. Anti-ciclo
-- -----------------------------------------------------------------------------
-- `A` accionista de `B` y `B` accionista de `A` pasa los CHECK de arriba y hace que
-- recorrer el árbol no termine nunca. Este trigger es la única defensa que cubre también
-- lo que entre por el back office o por SQL a mano; el límite de profundidad de la edge
-- function es la segunda red, no la primera.
--
-- SECURITY DEFINER a propósito: con RLS activa (§4), un cliente solo ve su propia rama.
-- Si el chequeo corriera con sus permisos, no vería el tramo del ciclo que vive en otra
-- rama y lo dejaría pasar. Tiene que ver la tabla completa.
CREATE OR REPLACE FUNCTION public.fn_personas_relacionadas_sin_ciclo()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_ciclo boolean;
BEGIN
  -- Un vínculo inactivo no forma parte del árbol, no puede cerrar un ciclo.
  IF NEW.activo IS NOT TRUE THEN
    RETURN NEW;
  END IF;

  -- ¿NEW.id_persona ya cuelga por debajo de NEW.id_persona_relacion? Si sí, agregar
  -- este vínculo cierra el ciclo.
  -- UNION (no UNION ALL) y el tope de nivel hacen que termine incluso si la tabla ya
  -- trajera un ciclo de antes.
  WITH RECURSIVE descendientes AS (
    SELECT pr.id_persona_relacion AS persona, 1 AS nivel
    FROM public.personas_relacionadas pr
    WHERE pr.id_persona = NEW.id_persona_relacion
      AND pr.activo
      AND (TG_OP <> 'UPDATE' OR pr.id <> NEW.id)

    UNION

    SELECT pr.id_persona_relacion, d.nivel + 1
    FROM public.personas_relacionadas pr
    JOIN descendientes d ON pr.id_persona = d.persona
    WHERE pr.activo
      AND d.nivel < 50
      AND (TG_OP <> 'UPDATE' OR pr.id <> NEW.id)
  )
  SELECT EXISTS (SELECT 1 FROM descendientes WHERE persona = NEW.id_persona)
    INTO v_ciclo;

  IF v_ciclo THEN
    RAISE EXCEPTION
      'Ciclo en personas_relacionadas: la persona % ya cuelga por debajo de % en el árbol',
      NEW.id_persona, NEW.id_persona_relacion
      USING ERRCODE = '23514';
  END IF;

  RETURN NEW;
END;
$function$;

-- Nace con EXECUTE para PUBLIC (y por tanto anon): se revoca.
REVOKE ALL ON FUNCTION public.fn_personas_relacionadas_sin_ciclo() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.fn_personas_relacionadas_sin_ciclo() FROM anon;
REVOKE ALL ON FUNCTION public.fn_personas_relacionadas_sin_ciclo() FROM authenticated;

DROP TRIGGER IF EXISTS trg_personas_relacionadas_sin_ciclo ON public.personas_relacionadas;
CREATE TRIGGER trg_personas_relacionadas_sin_ciclo
  BEFORE INSERT OR UPDATE ON public.personas_relacionadas
  FOR EACH ROW EXECUTE FUNCTION public.fn_personas_relacionadas_sin_ciclo();

-- Límite conocido: dos transacciones concurrentes que no se ven entre sí pueden cerrar
-- un ciclo entre las dos. El volumen de este flujo (alta manual desde el portal) lo hace
-- irrelevante; si algún día importa, va un advisory lock por raíz del árbol.

-- -----------------------------------------------------------------------------
-- §4. RLS
-- -----------------------------------------------------------------------------
-- Sin esto la tabla nace abierta: en este proyecto anon y authenticated tienen grants
-- sobre las tablas nuevas de `public`, y sin RLS PostgREST la expone entera. Aquí hay
-- estructura accionaria de los clientes.
--
-- Las altas del portal las escribe la edge function con service_role, que salta RLS.
-- Estas policies son para lo que consulte el panel directo.
ALTER TABLE public.personas_relacionadas ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.personas_relacionadas FROM anon;

DROP POLICY IF EXISTS personas_relacionadas_select ON public.personas_relacionadas;
CREATE POLICY personas_relacionadas_select
  ON public.personas_relacionadas
  FOR SELECT
  TO authenticated
  USING (
    public.user_has_internal_role(auth.uid())
    OR id_persona = public.current_persona_id()
    OR id_persona_relacion = public.current_persona_id()
  );

-- Back office: el personal interno también da de alta y de baja estos vínculos.
DROP POLICY IF EXISTS personas_relacionadas_interno_all ON public.personas_relacionadas;
CREATE POLICY personas_relacionadas_interno_all
  ON public.personas_relacionadas
  FOR ALL
  TO authenticated
  USING (public.user_has_internal_role(auth.uid()))
  WITH CHECK (public.user_has_internal_role(auth.uid()));

-- El cliente NO escribe directo: no hay policy de INSERT/UPDATE/DELETE para él. Su alta
-- pasa por la edge function, que ata el vínculo al id_persona del JWT y verifica que la
-- empresa esté en SU árbol.

-- Deja el id del catálogo en el log del deploy: no es el mismo en dev que en prod.
DO $log$
DECLARE
  v_id integer;
BEGIN
  SELECT id INTO v_id FROM public.tipos_relacion WHERE nombre = 'Accionista';

  IF v_id IS NULL THEN
    RAISE EXCEPTION 'No quedó registrado el tipo_relacion "Accionista"';
  END IF;

  RAISE NOTICE 'tipos_relacion "Accionista" → id %. El backend debe resolverlo por nombre, no clavarlo.', v_id;
END;
$log$;

COMMIT;

-- =============================================================================
-- Verificación (read-only, correr después del deploy)
-- =============================================================================
-- SELECT count(*) FROM public.personas_relacionadas;                    -- 0
-- SELECT id, nombre, tipo, activo FROM public.tipos_relacion WHERE nombre = 'Accionista';
--
-- SELECT conname, pg_get_constraintdef(oid) FROM pg_constraint
-- WHERE conrelid = 'public.personas_relacionadas'::regclass;
--
-- SELECT policyname, roles::text, cmd, qual FROM pg_policies
-- WHERE schemaname = 'public' AND tablename = 'personas_relacionadas';
--
-- UAT del anti-ciclo (transacción desechable, sustituir 101/102 por dos personas reales):
--   BEGIN;
--     INSERT INTO public.personas_relacionadas (id_persona, id_persona_relacion, id_tipo_relacion, porcentaje)
--     VALUES (101, 102, (SELECT id FROM tipos_relacion WHERE nombre='Accionista'), 30);
--     -- Esta debe fallar con 23514 (cierra el ciclo 101→102→101):
--     INSERT INTO public.personas_relacionadas (id_persona, id_persona_relacion, id_tipo_relacion, porcentaje)
--     VALUES (102, 101, (SELECT id FROM tipos_relacion WHERE nombre='Accionista'), 40);
--   ROLLBACK;
--
-- UAT del ciclo indirecto (A→B, B→C, C→A):
--   la tercera inserción debe fallar igual, porque A ya cuelga por debajo de C.
-- =============================================================================
