-- Perfil del Comprador por Negocio (CRM > Negocios).
-- Fecha: 2026-08-17
--
-- Tipifica de forma estandarizada al cliente que asiste a cita, por NEGOCIO
-- (relación 1:1 con crm_negocios). Los catálogos de opciones viven fijos en el
-- front; aquí se guardan como códigos TEXT (dropdowns) y TEXT[] (tags multi).
-- Habilita lectura rápida del contexto del prospecto y métricas de BI de perfil.
--
-- Reutiliza patrones vivos del CRM:
--   * fecha_actualizacion mantenida por public.crm_set_fecha_actualizacion().
--   * RLS espejo de crm_citas / crm_notas: authenticated lee/crea/actualiza,
--     borrado duro solo admin (public.is_admin_user()).
-- Idempotente y self-guarded. Sin BEGIN/COMMIT (el CI/CD envuelve en tx).

-- ─── crm_negocios_perfil_comprador ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.crm_negocios_perfil_comprador (
    id                    INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_negocio            INTEGER     NOT NULL UNIQUE
        REFERENCES public.crm_negocios(id) ON DELETE CASCADE,  -- 1:1 con el negocio
    -- 1. Demográficos y composición
    tipo_asistente        TEXT,   -- hombre_solo, mujer_sola, pareja, familia, socios, mystery_shopper
    rango_edad            TEXT,   -- menos_20, 20_30, 30_40, 40_50, 50_60, 60_mas
    toma_decision         TEXT,   -- individual, en_pareja, aprobacion_familiar, aprobacion_socio
    -- 2. Intención y madurez de compra
    intencion_uso         TEXT,   -- full_inversionista, hibrido, full_vivienda
    experiencia_preventa  TEXT,   -- primera_preventa, ya_compro_preventa
    etapa_exploracion     TEXT,   -- primer_desarrollo, ya_visito_otras
    competencia_visitada  TEXT,   -- campo abierto
    -- 3. Factores clave de la cita (multi-selección)
    puntos_positivos      TEXT[]  NOT NULL DEFAULT '{}',
    puntos_negativos      TEXT[]  NOT NULL DEFAULT '{}',
    -- 4. Ventana temporal de decisión
    proyeccion_cierre     TEXT,   -- inmediata, 1_mes, 2_meses, 3_mas
    -- Auditoría
    creado_por            UUID,   -- auth_user_id del asesor que llenó
    activo                BOOLEAN     NOT NULL DEFAULT TRUE,
    fecha_creacion        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_crm_perfil_comprador_negocio
    ON public.crm_negocios_perfil_comprador (id_negocio);

-- Trigger fecha_actualizacion: reutiliza la función compartida (no redefinir).
DROP TRIGGER IF EXISTS trg_crm_perfil_comprador_fecha_actualizacion ON public.crm_negocios_perfil_comprador;
CREATE TRIGGER trg_crm_perfil_comprador_fecha_actualizacion
BEFORE UPDATE ON public.crm_negocios_perfil_comprador
FOR EACH ROW EXECUTE FUNCTION public.crm_set_fecha_actualizacion();

-- ─── Row Level Security (espejo de crm_citas) ─────────────────────────────────
ALTER TABLE public.crm_negocios_perfil_comprador ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "crm_perfil_comprador_select" ON public.crm_negocios_perfil_comprador;
CREATE POLICY "crm_perfil_comprador_select" ON public.crm_negocios_perfil_comprador
    FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "crm_perfil_comprador_insert" ON public.crm_negocios_perfil_comprador;
CREATE POLICY "crm_perfil_comprador_insert" ON public.crm_negocios_perfil_comprador
    FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "crm_perfil_comprador_update" ON public.crm_negocios_perfil_comprador;
CREATE POLICY "crm_perfil_comprador_update" ON public.crm_negocios_perfil_comprador
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "crm_perfil_comprador_delete" ON public.crm_negocios_perfil_comprador;
CREATE POLICY "crm_perfil_comprador_delete" ON public.crm_negocios_perfil_comprador
    FOR DELETE TO authenticated USING (public.is_admin_user());

COMMENT ON TABLE public.crm_negocios_perfil_comprador IS
  'Perfil del comprador por negocio (1:1 con crm_negocios). Tipifica al cliente de la cita: demográficos, intención/madurez, puntos +/- y ventana de decisión. Catálogos fijos en el front.';
