-- Escenarios de precios compartidos entre usuarios
-- Fecha: 2026-08-22
-- Origen: Ejecuciones/ejecusiones.md
--
-- ─── Qué hace ─────────────────────────────────────────────────────────────────
-- Saca los escenarios de precios del navegador y los lleva a la base, para que todos los
-- usuarios vean los de todos y el Super Administrador pueda revisar el trabajo de
-- cualquiera.
--
-- Hoy `versionesStore` persiste en localStorage: un escenario guardado por un analista no
-- existe para nadie mas, ni para quien tiene que aprobarlo. No es un permiso que falte, es
-- que el dato nunca sale de esa maquina.
--
-- ─── Estado verificado read-only contra PRODUCCION el 2026-08-22 ──────────────
--   versiones_lista / precios_version   no existen
--   current_es_super_admin()            existe, SECURITY DEFINER, EXECUTE para authenticated
--   is_super_admin(uuid)                existe (y tambien una variante sin argumentos)
--   usuarios.auth_user_id               existe
--   pgcrypto                            instalada (gen_random_uuid de los UAT)
--
-- ─── Decisiones del documento que se conservan ────────────────────────────────
-- · Los precios van como jsonb en la MISMA fila, no en una tabla aparte. Es una divergencia
--   deliberada respecto a la nota de auditoria.ts, y la razon es la atomicidad: el cliente
--   de Supabase no abre transacciones, asi que con dos tablas un fallo a media insercion
--   dejaria una version sin precios —visible en la lista, vacia al abrirla— y nadie se
--   enteraria hasta usarla. Con una sola fila, la version existe completa o no existe.
-- · La inmutabilidad se aplica en la base. Una lista publicada es el precio con el que se
--   vendio; dejarlo en el store lo haria depender de que toda pantalla futura se acuerde.
-- · El numero de version lo asigna la base. Calcularlo en el cliente daria dos v3 en cuanto
--   dos personas guarden a la vez.
-- · Nadie borra: no hay politica de DELETE. Un escenario borrado se lleva la explicacion de
--   por que un precio fue el que fue.
--
-- ─── Lo que se añade al DDL del documento ─────────────────────────────────────
-- 1) REVOKE de `anon` y GRANT explicito SIN DELETE. Las default privileges de Supabase
--    conceden a `anon` y a `authenticated` TODOS los privilegios sobre cada tabla nueva de
--    `public`, DELETE incluido. Hoy RLS lo frena por los dos lados —anon no tiene ninguna
--    politica y el DELETE no tiene politica para nadie— pero el privilegio quedaria puesto:
--    la primera policy permisiva que alguien agregue abriria el borrado que este diseño
--    quiere impedir. Revocarlo hace que la intencion del documento la sostengan dos capas y
--    no una.
-- 2) `SET search_path` en el trigger de inmutabilidad. El documento se lo pone al de
--    numeracion pero no a este; es el patron del repo para toda funcion nueva.
--
-- Idempotente: CREATE ... IF NOT EXISTS, CREATE OR REPLACE y DROP TRIGGER/POLICY antes de
-- crear. Sin BEGIN/COMMIT (el CI envuelve cada archivo, y un COMMIT explicito dejaria fuera
-- el registro en schema_migrations).

-- ═══════════════════════════════════════════════════════════════════════════════
-- 0. Guard previo: las funciones de rol que usan las policies deben existir
-- ═══════════════════════════════════════════════════════════════════════════════
DO $guard$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public' AND p.proname = 'current_es_super_admin'
      AND pg_get_function_identity_arguments(p.oid) = ''
  ) THEN
    RAISE EXCEPTION
      'No existe public.current_es_super_admin(): las policies de alta y edicion dependen de ella.';
  END IF;
END
$guard$;

-- ═══════════════════════════════════════════════════════════════════════════════
-- 1. La tabla
--    `id` es GENERATED BY DEFAULT (no ALWAYS) a proposito: permite insertar un id
--    explicito si algun dia se migra lo que hoy vive en localStorage.
-- ═══════════════════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.versiones_lista (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_proyecto           integer NOT NULL REFERENCES public.proyectos (id),
  numero                integer NOT NULL,
  nombre                text    NOT NULL,
  estado                text    NOT NULL DEFAULT 'borrador',

  -- Quien y cuando. El uuid liga con auth.uid(); el nombre y el rol se guardan copiados
  -- para que la lista se pueda leer sin ir a buscar al usuario, y para que siga diciendo
  -- algo si esa persona se da de baja.
  creada_en             timestamptz NOT NULL DEFAULT now(),
  creada_por            uuid    NOT NULL DEFAULT auth.uid(),
  creada_por_nombre     text    NOT NULL DEFAULT '',
  creada_por_rol        text    NOT NULL DEFAULT '',
  publicada_en          timestamptz,
  publicada_por         uuid,
  publicada_por_nombre  text,

  -- El motor completo con el que se calculo, y el precio de cada unidad.
  snapshot_motor        jsonb   NOT NULL,
  precios               jsonb   NOT NULL DEFAULT '{}'::jsonb,
  unidades_incluidas    jsonb   NOT NULL DEFAULT '[]'::jsonb,
  unidades_excluidas    jsonb   NOT NULL DEFAULT '[]'::jsonb,

  valor_total           numeric(18,2) NOT NULL DEFAULT 0,
  notas                 text    NOT NULL DEFAULT '',

  CONSTRAINT versiones_lista_estado_chk
    CHECK (estado IN ('borrador', 'publicada', 'archivada')),
  CONSTRAINT versiones_lista_numero_chk CHECK (numero > 0)
);

-- Dos personas guardando a la vez no pueden producir dos v3 del mismo proyecto.
CREATE UNIQUE INDEX IF NOT EXISTS versiones_lista_numero_por_proyecto
  ON public.versiones_lista (id_proyecto, numero);

CREATE INDEX IF NOT EXISTS versiones_lista_por_proyecto
  ON public.versiones_lista (id_proyecto, creada_en DESC);

-- ═══════════════════════════════════════════════════════════════════════════════
-- 2. Numeración por proyecto, asignada por la base
--    Se respeta un numero enviado explicitamente por si hace falta migrar lo de
--    localStorage conservando su historia; si no viene, se toma el siguiente.
--
--    OJO: leer MAX() no serializa nada. Dos inserciones simultaneas leen el mismo maximo y
--    la segunda choca contra el indice unico con 23505; eso es deliberado —el indice es la
--    garantia real— pero significa que el cliente debe reintentar ante ese codigo, no
--    tratarlo como error definitivo.
-- ═══════════════════════════════════════════════════════════════════════════════
CREATE OR REPLACE FUNCTION public.versiones_lista_numerar()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $fn$
BEGIN
  IF NEW.numero IS NULL OR NEW.numero <= 0 THEN
    SELECT COALESCE(MAX(numero), 0) + 1 INTO NEW.numero
    FROM public.versiones_lista
    WHERE id_proyecto = NEW.id_proyecto;
  END IF;
  RETURN NEW;
END;
$fn$;

DROP TRIGGER IF EXISTS trg_versiones_lista_numerar ON public.versiones_lista;
CREATE TRIGGER trg_versiones_lista_numerar
  BEFORE INSERT ON public.versiones_lista
  FOR EACH ROW EXECUTE FUNCTION public.versiones_lista_numerar();

-- ═══════════════════════════════════════════════════════════════════════════════
-- 3. Una lista publicada es el precio con el que se vendió: no se edita
--    La unica transicion permitida desde 'publicada' es archivarla, y eso solo toca la
--    columna de estado. Vive en la base y no en el front porque si no dependeria de que
--    toda pantalla futura se acuerde de respetarlo.
-- ═══════════════════════════════════════════════════════════════════════════════
CREATE OR REPLACE FUNCTION public.versiones_lista_inmutable()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $fn$
BEGIN
  IF OLD.estado = 'publicada' THEN
    IF NEW.estado = 'archivada'
       AND NEW.snapshot_motor IS NOT DISTINCT FROM OLD.snapshot_motor
       AND NEW.precios        IS NOT DISTINCT FROM OLD.precios
       AND NEW.valor_total    IS NOT DISTINCT FROM OLD.valor_total THEN
      RETURN NEW;
    END IF;
    RAISE EXCEPTION
      'La version v% esta publicada y es inmutable: solo puede archivarse.', OLD.numero
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END;
$fn$;

DROP TRIGGER IF EXISTS trg_versiones_lista_inmutable ON public.versiones_lista;
CREATE TRIGGER trg_versiones_lista_inmutable
  BEFORE UPDATE ON public.versiones_lista
  FOR EACH ROW EXECUTE FUNCTION public.versiones_lista_inmutable();

-- ═══════════════════════════════════════════════════════════════════════════════
-- 4. RLS: tres reglas, ninguna de borrado
-- ═══════════════════════════════════════════════════════════════════════════════
ALTER TABLE public.versiones_lista ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS versiones_lista_lectura ON public.versiones_lista;
DROP POLICY IF EXISTS versiones_lista_alta    ON public.versiones_lista;
DROP POLICY IF EXISTS versiones_lista_edicion ON public.versiones_lista;

-- Todos los autenticados ven todos los escenarios: ese es el punto del cambio.
CREATE POLICY versiones_lista_lectura
  ON public.versiones_lista FOR SELECT TO authenticated
  USING (true);

-- Cada quien da de alta a su nombre. Sin esto, un escenario podria nacer firmado por
-- alguien mas.
CREATE POLICY versiones_lista_alta
  ON public.versiones_lista FOR INSERT TO authenticated
  WITH CHECK (creada_por = auth.uid() OR public.current_es_super_admin());

-- Edita el autor, o el Super Administrador sobre cualquiera: un escenario mal nombrado por
-- quien ya no esta en la empresa no puede quedar congelado.
CREATE POLICY versiones_lista_edicion
  ON public.versiones_lista FOR UPDATE TO authenticated
  USING (creada_por = auth.uid() OR public.current_es_super_admin())
  WITH CHECK (creada_por = auth.uid() OR public.current_es_super_admin());

-- Sin politica de DELETE a proposito: el camino para retirar un escenario es archivarlo.

-- ═══════════════════════════════════════════════════════════════════════════════
-- 5. Privilegios
--    Se revoca `anon` por completo y se otorga a `authenticated` todo MENOS DELETE, para
--    que la prohibicion de borrar la sostengan el privilegio y la ausencia de policy, no
--    solo la segunda.
-- ═══════════════════════════════════════════════════════════════════════════════
REVOKE ALL PRIVILEGES ON TABLE public.versiones_lista FROM anon;
REVOKE DELETE, TRUNCATE ON TABLE public.versiones_lista FROM authenticated;

GRANT SELECT, INSERT, UPDATE ON TABLE public.versiones_lista TO authenticated;
GRANT SELECT, INSERT, UPDATE ON TABLE public.versiones_lista TO service_role;
-- No se otorga nada sobre la secuencia: `id` es una columna IDENTITY, y a diferencia de
-- `serial` no exige privilegios sobre su secuencia. Nombrarla aqui solo agregaria un punto
-- de fallo si el nombre generado no coincidiera.

COMMENT ON TABLE public.versiones_lista IS
  'Escenarios y versiones de lista de precios del modulo Precios. Compartidos entre '
  'usuarios: todos los autenticados leen todos. Una version publicada es inmutable (solo '
  'puede archivarse) y nadie puede borrar: no hay policy ni privilegio de DELETE.';
COMMENT ON COLUMN public.versiones_lista.precios IS
  'Snapshot por unidad: { id_propiedad: { precio_calculado, precio_override, precio_lista, '
  'componente_exento, componente_gravado } }. Va en la misma fila que la version, no en una '
  'tabla aparte, para que la version exista completa o no exista: el cliente de Supabase no '
  'abre transacciones.';
COMMENT ON COLUMN public.versiones_lista.snapshot_motor IS
  'Configuracion completa del motor con la que se calculo esta lista.';
COMMENT ON COLUMN public.versiones_lista.creada_por IS
  'auth.uid() del autor. Tiene DEFAULT auth.uid(), asi que una insercion sin sesion —por '
  'ejemplo con service_role desde una Edge Function— debe enviarlo explicitamente o violara '
  'el NOT NULL.';

-- ═══════════════════════════════════════════════════════════════════════════════
-- 6. Guard de cierre
-- ═══════════════════════════════════════════════════════════════════════════════
DO $cierre$
DECLARE
  v_pols     int;
  v_delete   int;
  v_triggers int;
  v_rls      boolean;
BEGIN
  SELECT count(*) INTO v_pols FROM pg_policies WHERE tablename = 'versiones_lista';
  IF v_pols <> 3 THEN
    RAISE EXCEPTION 'Se esperaban 3 policies (SELECT, INSERT, UPDATE) y hay %.', v_pols;
  END IF;

  SELECT count(*) INTO v_delete
  FROM pg_policies WHERE tablename = 'versiones_lista' AND cmd = 'DELETE';
  IF v_delete <> 0 THEN
    RAISE EXCEPTION 'Hay % policy de DELETE: este diseño no permite borrar escenarios.', v_delete;
  END IF;

  SELECT count(*) INTO v_triggers
  FROM pg_trigger
  WHERE tgrelid = 'public.versiones_lista'::regclass AND NOT tgisinternal;
  IF v_triggers <> 2 THEN
    RAISE EXCEPTION 'Se esperaban los 2 triggers (numerar, inmutable) y hay %.', v_triggers;
  END IF;

  SELECT relrowsecurity INTO v_rls FROM pg_class WHERE oid = 'public.versiones_lista'::regclass;
  IF NOT v_rls THEN
    RAISE EXCEPTION 'RLS no quedo habilitado: cualquier autenticado editaria escenarios ajenos.';
  END IF;

  IF has_table_privilege('authenticated', 'public.versiones_lista', 'DELETE') THEN
    RAISE EXCEPTION 'authenticated conserva el privilegio DELETE: el REVOKE no surtio efecto.';
  END IF;

  IF has_table_privilege('anon', 'public.versiones_lista', 'SELECT') THEN
    RAISE EXCEPTION 'anon conserva privilegios sobre versiones_lista.';
  END IF;

  RAISE NOTICE
    'versiones_lista lista: RLS activo, 3 policies sin DELETE, 2 triggers, anon revocado.';
END
$cierre$;

-- ─── Validación (post-deploy, read-only) ──────────────────────────────────────
--   SELECT policyname, cmd FROM pg_policies
--   WHERE tablename='versiones_lista' ORDER BY cmd;
--   -- esperado: SELECT, INSERT, UPDATE. Sin DELETE.
--
--   SELECT tgname FROM pg_trigger
--   WHERE tgrelid='public.versiones_lista'::regclass AND NOT tgisinternal;
--   -- esperado: trg_versiones_lista_numerar, trg_versiones_lista_inmutable
--
--   SELECT grantee, privilege_type FROM information_schema.role_table_grants
--   WHERE table_schema='public' AND table_name='versiones_lista'
--     AND grantee IN ('anon','authenticated') ORDER BY grantee, privilege_type;
--   -- esperado: anon sin filas; authenticated con SELECT, INSERT, UPDATE y sin DELETE
--
--   SELECT count(*) FROM public.versiones_lista;   -- esperado: 0, nace vacia
--
-- ═══════════════════════════════════════════════════════════════════════════════
-- TRES COSAS QUE CONVIENE SABER ANTES DE CONSTRUIR CONTRA ESTA TABLA
-- ═══════════════════════════════════════════════════════════════════════════════
--
-- 1) EL SUPER ADMINISTRADOR TAMPOCO PUEDE RENOMBRAR UNA PUBLICADA.
--    El diagnostico justifica darle UPDATE sobre cualquiera con el caso del "escenario mal
--    nombrado por quien ya no esta en la empresa". Eso funciona en borradores, pero el
--    trigger de inmutabilidad se aplica a TODOS por igual: sobre una publicada, el unico
--    UPDATE que pasa es archivarla. Es coherente con que sea el precio con el que se
--    vendio, pero significa que un nombre equivocado en una lista ya publicada se queda
--    asi. Si eso no es lo deseado, la excepcion tendria que escribirse en el trigger.
--
-- 2) LA NUMERACION PUEDE DAR 23505 EN CONCURRENCIA, POR DISEÑO.
--    El trigger lee MAX(numero) y eso no serializa: dos altas simultaneas en el mismo
--    proyecto obtienen el mismo numero y la segunda choca contra el indice unico. El
--    documento lo dice —"el indice unico es lo que garantiza que no se repita"— asi que el
--    front debe reintentar ante 23505 en vez de mostrar un error definitivo.
--
-- 3) `creada_por` NO ADMITE INSERCIONES SIN SESION.
--    Es NOT NULL con DEFAULT auth.uid(), que devuelve NULL cuando no hay JWT. Una insercion
--    con service_role —una Edge Function, un job— debe enviar el uuid explicitamente o
--    violara el NOT NULL. Hoy el modulo escribe desde el navegador como authenticated, asi
--    que no aplica; queda anotado para el dia que se automatice.
--
-- ─── Front ────────────────────────────────────────────────────────────────────
-- El modulo ya hace prueba de existencia de la tabla: mientras no este, guarda en
-- localStorage y avisa en pantalla que los escenarios no se comparten. Al aplicarse empieza
-- a usarla sin ningun cambio.
--
-- Lo que ya esta en localStorage NO se migra solo. Si hay escenarios que valga la pena
-- conservar, hay que volver a guardarlos con el motor retomado.
