-- Adjuntos de los COMENTARIOS de notas del CRM: imágenes (incl. pegadas con Ctrl+V),
-- archivos y notas de voz. Un comentario (fila de `crm_notas_comentarios`) puede tener N
-- adjuntos. El binario vive en Storage (bucket `documentos`, prefijo `crm-notes/`); aquí
-- solo la referencia. Espejo de `crm_notas_adjuntos`.
-- RLS: authenticated lee/crea/actualiza (soft-delete vía activo=false), borrado duro solo admin.
-- Idempotente y self-guarded para no romper el CI si se re-corre. Sin BEGIN/COMMIT
-- (supabase db push envuelve cada migración en su propia transacción).

CREATE TABLE IF NOT EXISTS public.crm_notas_comentarios_adjuntos (
    id              INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_comentario   INTEGER      NOT NULL
        REFERENCES public.crm_notas_comentarios(id) ON DELETE CASCADE,
    tipo            TEXT         NOT NULL
        CHECK (tipo IN ('image', 'file', 'audio')),
    url             TEXT         NOT NULL,
    nombre          TEXT         NOT NULL,
    mime            TEXT,
    tamano_bytes    BIGINT,
    id_usuario      UUID,
    activo          BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_crm_notas_comentarios_adjuntos_comentario
    ON public.crm_notas_comentarios_adjuntos (id_comentario);

-- ─── Row Level Security ───────────────────────────────────────────────────────
ALTER TABLE public.crm_notas_comentarios_adjuntos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "crm_notas_comentarios_adjuntos_select" ON public.crm_notas_comentarios_adjuntos;
CREATE POLICY "crm_notas_comentarios_adjuntos_select" ON public.crm_notas_comentarios_adjuntos
    FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "crm_notas_comentarios_adjuntos_insert" ON public.crm_notas_comentarios_adjuntos;
CREATE POLICY "crm_notas_comentarios_adjuntos_insert" ON public.crm_notas_comentarios_adjuntos
    FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "crm_notas_comentarios_adjuntos_update" ON public.crm_notas_comentarios_adjuntos;
CREATE POLICY "crm_notas_comentarios_adjuntos_update" ON public.crm_notas_comentarios_adjuntos
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "crm_notas_comentarios_adjuntos_delete" ON public.crm_notas_comentarios_adjuntos;
CREATE POLICY "crm_notas_comentarios_adjuntos_delete" ON public.crm_notas_comentarios_adjuntos
    FOR DELETE TO authenticated USING (is_admin_user());
