-- Citas del CRM: reuniones / juntas como actividad nativa por contacto.
-- Fecha: 2026-07-21
--
-- Espejo de `crm_tareas`: un "contacto" del CRM = una fila de
-- `entidades_relacionadas` (prospecto tipo 7 / comprador tipo 2), y esta tabla
-- cuelga de `id_entidad_relacionada`. A diferencia de la tarea, la cita tiene
-- una ventana de tiempo (fecha_inicio / fecha_fin), lugar/enlace y resultado.
--
-- Reutiliza los patrones ya vivos del CRM:
--   * fecha_actualizacion mantenida por la función compartida
--     public.crm_set_fecha_actualizacion() (ver 20260721080000_*), sin redefinirla.
--   * fecha_recordatorio / recordatorio_enviado igual que crm_tareas, para
--     reciclar el patrón de recordatorios (sin cron por ahora).
--   * RLS espejo de crm_notas / crm_tareas: authenticated lee/crea/actualiza,
--     borrado duro solo admin.
--
-- Idempotente y self-guarded (CREATE TABLE IF NOT EXISTS, CREATE INDEX IF NOT
-- EXISTS, DROP POLICY/TRIGGER IF EXISTS) para no romper el CI si se re-corre.
-- Sin BEGIN/COMMIT (el CI/CD envuelve en tx).

-- ─── crm_citas ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.crm_citas (
    id                      INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_entidad_relacionada  BIGINT       NOT NULL
        REFERENCES public.entidades_relacionadas(id) ON DELETE CASCADE,  -- el contacto del CRM
    id_usuario_asignado     UUID,        -- auth_user_id del asesor organizador
    titulo                  TEXT         NOT NULL,
    tipo                    TEXT         NOT NULL DEFAULT 'presencial',  -- presencial, videollamada, llamada, visita_obra, showroom
    estatus                 TEXT         NOT NULL DEFAULT 'programada',  -- programada, realizada, no_asistio, cancelada, reprogramada
    fecha_inicio            TIMESTAMPTZ, -- inicio de la cita
    fecha_fin               TIMESTAMPTZ, -- fin de la cita (opcional; el front calcula desde duración)
    ubicacion               TEXT,        -- dirección / lugar físico
    enlace_reunion          TEXT,        -- URL de videollamada
    resultado               TEXT,        -- notas del resultado de la cita (opcional)
    descripcion             TEXT,        -- agenda / notas / detalle
    fecha_recordatorio      TIMESTAMPTZ, -- momento del recordatorio (patrón crm_tareas; sin cron por ahora)
    recordatorio_enviado    BOOLEAN      NOT NULL DEFAULT FALSE,
    activo                  BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    fecha_actualizacion     TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_crm_citas_er
    ON public.crm_citas (id_entidad_relacionada);
CREATE INDEX IF NOT EXISTS idx_crm_citas_asignado
    ON public.crm_citas (id_usuario_asignado);
CREATE INDEX IF NOT EXISTS idx_crm_citas_fecha_inicio
    ON public.crm_citas (fecha_inicio);

-- Trigger fecha_actualizacion: reutiliza la función compartida (no redefinir).
DROP TRIGGER IF EXISTS trg_crm_citas_fecha_actualizacion ON public.crm_citas;
CREATE TRIGGER trg_crm_citas_fecha_actualizacion
BEFORE UPDATE ON public.crm_citas
FOR EACH ROW EXECUTE FUNCTION public.crm_set_fecha_actualizacion();

-- ─── Row Level Security ───────────────────────────────────────────────────────
-- Actividad interna del equipo de ventas: lectura/escritura para autenticados,
-- borrado solo admin.
ALTER TABLE public.crm_citas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "crm_citas_select" ON public.crm_citas;
CREATE POLICY "crm_citas_select" ON public.crm_citas
    FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "crm_citas_insert" ON public.crm_citas;
CREATE POLICY "crm_citas_insert" ON public.crm_citas
    FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "crm_citas_update" ON public.crm_citas;
CREATE POLICY "crm_citas_update" ON public.crm_citas
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "crm_citas_delete" ON public.crm_citas;
CREATE POLICY "crm_citas_delete" ON public.crm_citas
    FOR DELETE TO authenticated USING (public.is_admin_user());
